/** CRM category-hub tool profiles — generated by scripts/seed-crm-hub.ts via claude-sonnet-4-6.
 *  Merged into REVIEW_KNOWN (ReviewTemplate) and KNOWN (HubTemplate). Re-run to refresh. */
import type { ReviewProfile } from '@/components/templates/ReviewTemplate';

export const CRM_REVIEW_KNOWN: Record<string, Partial<ReviewProfile>> = {
  "salesforce-einstein-crm": {
    "logo": "bg-indigo-600",
    "ctaName": "Salesforce Einstein",
    "fallbackUrl": "https://www.salesforce.com/products/einstein/",
    "company": "Salesforce",
    "model": "Einstein CRM 2026",
    "founded": 1999,
    "hq": "San Francisco, USA",
    "useCases": [
      "Enterprise-säljteam med komplexa pipelines",
      "Prediktiv lead- och affärsanalys",
      "Automatiserad kundkommunikation i stor skala",
      "Flerkanalig kundservice med AI-stöd",
      "Detaljerad intäktsprognostisering"
    ],
    "ratingCriteria": [
      {
        "label": "AI-funktioner",
        "score": 9.7
      },
      {
        "label": "Lead scoring",
        "score": 9.6
      },
      {
        "label": "Automation",
        "score": 9.4
      },
      {
        "label": "Integrationer",
        "score": 9.8
      },
      {
        "label": "Pris/prestanda",
        "score": 7.5
      },
      {
        "label": "Användarvänlighet",
        "score": 7.8
      }
    ],
    "tags": [
      "Enterprise",
      "Prediktiv AI",
      "Skalbar",
      "Ekosystem"
    ],
    "pros": [
      "Branschledande AI-modeller med djup anpassning",
      "Extremt brett integrationsekosystem via AppExchange",
      "Kraftfull intäktsprognostisering med Einstein Forecasting"
    ],
    "cons": [
      "Hög totalkostnad gör det olämpligt för mindre bolag",
      "Brant inlärningskurva och lång implementationstid"
    ],
    "offer": {
      "title": "Salesforce Einstein",
      "price": "Starter Suite från 25 USD/användare/mån · Einstein-tillägg från 50 USD/användare/mån",
      "bestFor": "Stora enterprise-organisationer med dedikerade CRM-team"
    },
    "label": "Enterprise-standard",
    "score": 9
  },
  "hubspot-ai-crm": {
    "logo": "bg-emerald-500",
    "ctaName": "HubSpot AI",
    "fallbackUrl": "https://www.hubspot.com",
    "company": "HubSpot",
    "model": "HubSpot AI CRM 2026",
    "founded": 2006,
    "hq": "Cambridge, USA",
    "useCases": [
      "Inbound-marknadsföring kopplad till CRM",
      "AI-driven innehållsgenerering för säljteam",
      "Automatiserade e-postsekvenser med personalisering",
      "Lead-nurturing för tillväxtbolag",
      "Enhetlig vy över marknadsföring, sälj och support"
    ],
    "ratingCriteria": [
      {
        "label": "AI-funktioner",
        "score": 9.1
      },
      {
        "label": "Lead scoring",
        "score": 8.9
      },
      {
        "label": "Automation",
        "score": 9.3
      },
      {
        "label": "Integrationer",
        "score": 9.2
      },
      {
        "label": "Pris/prestanda",
        "score": 8.6
      },
      {
        "label": "Användarvänlighet",
        "score": 9.5
      }
    ],
    "tags": [
      "Inbound",
      "Allt-i-ett",
      "Skalbar",
      "Användarvänlig"
    ],
    "pros": [
      "Sömlös integrering av marknadsföring, sälj och service i en plattform",
      "Generöst gratisnivå som ger verkligt värde",
      "Mycket intuitiv upplevelse som sänker onboardingtiden"
    ],
    "cons": [
      "Kostnaderna stiger snabbt när kontaktdatabasen växer",
      "Avancerade AI-funktioner är låsta bakom dyrare planer"
    ],
    "offer": {
      "title": "HubSpot AI CRM",
      "price": "Gratis · Starter från 20 USD/mån · Professional från 890 USD/mån",
      "bestFor": "Tillväxtbolag som vill samla sälj och marknad i ett verktyg"
    },
    "label": "Redaktionens val",
    "score": 9.1
  },
  "pipedrive-ai": {
    "logo": "bg-orange-500",
    "ctaName": "Pipedrive AI",
    "fallbackUrl": "https://www.pipedrive.com",
    "company": "Pipedrive",
    "model": "Pipedrive AI 2026",
    "founded": 2010,
    "hq": "Tallinn, Estland",
    "useCases": [
      "Visuell pipeline-hantering för säljteam",
      "AI-baserade nästa-steg-rekommendationer",
      "Automatiserad uppföljning av affärer som riskerar att stanna",
      "Säljcoachning baserad på aktivitetsdata",
      "SMB-säljcykler med tydlig struktur"
    ],
    "ratingCriteria": [
      {
        "label": "AI-funktioner",
        "score": 8.4
      },
      {
        "label": "Lead scoring",
        "score": 8.6
      },
      {
        "label": "Automation",
        "score": 8.7
      },
      {
        "label": "Integrationer",
        "score": 8.5
      },
      {
        "label": "Pris/prestanda",
        "score": 9
      },
      {
        "label": "Användarvänlighet",
        "score": 9.4
      }
    ],
    "tags": [
      "SMB",
      "Pipeline-fokus",
      "Säljdriven",
      "Enkel setup"
    ],
    "pros": [
      "Exceptionellt tydlig och visuell pipelinevy",
      "Snabb implementation utan teknisk personal",
      "Konkurrenskraftigt pris för funktionaliteten"
    ],
    "cons": [
      "AI-funktionerna är grundläggande jämfört med enterprise-alternativ",
      "Begränsade möjligheter för komplex marknadsföringsautomation"
    ],
    "offer": {
      "title": "Pipedrive AI",
      "price": "Essential från 14 USD/användare/mån · Advanced från 34 USD/användare/mån",
      "bestFor": "Säljfokuserade SMB-team som vill ha enkel men strukturerad pipeline"
    },
    "label": "Bäst för SMB-sälj",
    "score": 8.7
  },
  "zoho-ai": {
    "logo": "bg-sky-500",
    "ctaName": "Zoho AI",
    "fallbackUrl": "https://www.zoho.com/crm/",
    "company": "Zoho",
    "model": "Zoho CRM med Zia AI 2026",
    "founded": 1996,
    "hq": "Chennai, Indien",
    "useCases": [
      "Prismedveten skalning av CRM-funktioner",
      "AI-assistenten Zia för anomalidetektion och förslag",
      "Flerkanalig kundkommunikation via en plattform",
      "Automatiserade arbetsflöden i komplexa processer",
      "Integrering med Zohos breda appsvit"
    ],
    "ratingCriteria": [
      {
        "label": "AI-funktioner",
        "score": 8.5
      },
      {
        "label": "Lead scoring",
        "score": 8.3
      },
      {
        "label": "Automation",
        "score": 8.8
      },
      {
        "label": "Integrationer",
        "score": 9
      },
      {
        "label": "Pris/prestanda",
        "score": 9.6
      },
      {
        "label": "Användarvänlighet",
        "score": 8.2
      }
    ],
    "tags": [
      "Prisvärd",
      "Ekosystem",
      "Automation",
      "Mångsidig"
    ],
    "pros": [
      "Överlägsen pris/prestanda-kvot i sin klass",
      "Djup integrering med hela Zoho-ekosystemet",
      "Zia AI levererar genuint användbara anomali- och trendvarningar"
    ],
    "cons": [
      "Användargränssnittet känns ålderdomligt i jämförelse med nyare konkurrenter",
      "Teknisk support kan vara långsam utanför premium-planer"
    ],
    "offer": {
      "title": "Zoho CRM Plus",
      "price": "Gratis upp till 3 användare · Standard från 14 USD/användare/mån · Ultimate från 52 USD/användare/mån",
      "bestFor": "Kostnadsmedvetna bolag som vill ha bred funktionalitet utan hög prislapp"
    },
    "label": "Bäst pris/prestanda",
    "score": 8.6
  },
  "monday-crm-ai": {
    "logo": "bg-violet-600",
    "ctaName": "Monday CRM AI",
    "fallbackUrl": "https://monday.com/crm",
    "company": "Monday.com",
    "model": "Monday CRM AI 2026",
    "founded": 2012,
    "hq": "Tel Aviv, Israel",
    "useCases": [
      "Visuell projektdriven säljhantering",
      "Samarbete mellan sälj och övriga affärsenheter",
      "Anpassningsbara workflows utan kodkunskap",
      "AI-genererade sammanfattningar av affärsstatus",
      "Hybridteam som blandar projekt och kundhantering"
    ],
    "ratingCriteria": [
      {
        "label": "AI-funktioner",
        "score": 8.2
      },
      {
        "label": "Lead scoring",
        "score": 7.8
      },
      {
        "label": "Automation",
        "score": 8.5
      },
      {
        "label": "Integrationer",
        "score": 8.7
      },
      {
        "label": "Pris/prestanda",
        "score": 8.3
      },
      {
        "label": "Användarvänlighet",
        "score": 9.3
      }
    ],
    "tags": [
      "Visuell",
      "Flexibel",
      "Samarbete",
      "No-code"
    ],
    "pros": [
      "Exceptionellt flexibel plattform som anpassas till olika arbetsflöden",
      "Stark visuell överskådlighet som underlättar teamsamarbete",
      "Enkel att sätta upp utan teknisk bakgrund"
    ],
    "cons": [
      "Lead scoring och prediktiva AI-funktioner är underutvecklade",
      "Kan bli rörigt att underhålla när antalet boards växer"
    ],
    "offer": {
      "title": "Monday CRM AI",
      "price": "Basic från 12 USD/plats/mån · Pro från 24 USD/plats/mån",
      "bestFor": "Team som vill ha ett CRM tätt integrerat med projekthantering"
    },
    "label": "Bäst för hybridteam",
    "score": 8.4
  },
  "freshsales-ai": {
    "logo": "bg-rose-500",
    "ctaName": "Freshsales AI",
    "fallbackUrl": "https://www.freshworks.com/crm/",
    "company": "Freshworks",
    "model": "Freshsales med Freddy AI 2026",
    "founded": 2010,
    "hq": "San Mateo, USA",
    "useCases": [
      "AI-driven lead scoring med Freddy Insights",
      "Automatiserade säljsekvenser för inkommande leads",
      "Konversationsanalys av telefonsamtal och e-post",
      "Kundservice kopplad direkt till säljdata",
      "Mellanstora B2B-säljorganisationer"
    ],
    "ratingCriteria": [
      {
        "label": "AI-funktioner",
        "score": 8.7
      },
      {
        "label": "Lead scoring",
        "score": 9
      },
      {
        "label": "Automation",
        "score": 8.9
      },
      {
        "label": "Integrationer",
        "score": 8.6
      },
      {
        "label": "Pris/prestanda",
        "score": 8.8
      },
      {
        "label": "Användarvänlighet",
        "score": 8.9
      }
    ],
    "tags": [
      "Freddy AI",
      "Lead scoring",
      "B2B",
      "Konversationsanalys"
    ],
    "pros": [
      "Freddy AI erbjuder genuint stark och förklarbar lead scoring",
      "Bra balans mellan funktionalitet och pris för mellanstora team",
      "Inbyggd konversationsintelligens som analyserar samtal automatiskt"
    ],
    "cons": [
      "Integrationsbiblioteket är smalare än Salesforce och HubSpot",
      "Rapporteringsverktyget saknar djup för avancerad analys"
    ],
    "offer": {
      "title": "Freshsales AI",
      "price": "Gratis upp till 3 användare · Growth från 11 USD/användare/mån · Pro från 47 USD/användare/mån",
      "bestFor": "Mellanstora säljteam som prioriterar AI-driven prioritering av leads"
    },
    "label": "Starkast lead scoring",
    "score": 8.8
  },
  "close-ai": {
    "logo": "bg-amber-500",
    "ctaName": "Close AI",
    "fallbackUrl": "https://www.close.com",
    "company": "Close",
    "model": "Close AI 2026",
    "founded": 2013,
    "hq": "San Francisco, USA",
    "useCases": [
      "Insäljning och telefonstyrda säljprocesser",
      "AI-transkription och sammanfattning av samtal",
      "Automatiserade e-post- och SMS-sekvenser",
      "Snabb uppföljning av inkommande leads",
      "Distansbaserade säljteam med fokus på volym"
    ],
    "ratingCriteria": [
      {
        "label": "AI-funktioner",
        "score": 8.6
      },
      {
        "label": "Lead scoring",
        "score": 8.4
      },
      {
        "label": "Automation",
        "score": 9.2
      },
      {
        "label": "Integrationer",
        "score": 8
      },
      {
        "label": "Pris/prestanda",
        "score": 8.7
      },
      {
        "label": "Användarvänlighet",
        "score": 9.1
      }
    ],
    "tags": [
      "Insäljning",
      "Samtalsfokus",
      "Automation",
      "Distanssälj"
    ],
    "pros": [
      "Inbyggd VoIP med AI-transkription är exceptionellt bra",
      "Automationssekvenser för e-post och SMS är snabba att konfigurera",
      "Designat specifikt för insäljning vilket syns i varje detalj"
    ],
    "cons": [
      "Begränsade funktioner för komplex pipeline-hantering på enterprise-nivå",
      "Integrationsytan är smalare än de bredare plattformarna"
    ],
    "offer": {
      "title": "Close AI",
      "price": "Startup från 49 USD/mån · Professional från 99 USD/mån · Enterprise från 139 USD/mån",
      "bestFor": "Insäljningsteam som arbetar med hög samtalsvolym och snabba cykler"
    },
    "label": "Bäst för insäljning",
    "score": 8.7
  },
  "attio": {
    "logo": "bg-teal-500",
    "ctaName": "Attio",
    "fallbackUrl": "https://attio.com",
    "company": "Attio",
    "model": "Attio 2026",
    "founded": 2019,
    "hq": "London, Storbritannien",
    "useCases": [
      "Datarika relationsgrafer för investerare och VC-bolag",
      "Flexibel CRM-struktur utan förutbestämda objekt",
      "AI-berikning av kontakt- och bolagsdata",
      "Startup- och scale-up-säljprocesser",
      "Team som vill bygga egna CRM-strukturer från grunden"
    ],
    "ratingCriteria": [
      {
        "label": "AI-funktioner",
        "score": 8.3
      },
      {
        "label": "Lead scoring",
        "score": 7.9
      },
      {
        "label": "Automation",
        "score": 8.1
      },
      {
        "label": "Integrationer",
        "score": 8.4
      },
      {
        "label": "Pris/prestanda",
        "score": 8.5
      },
      {
        "label": "Användarvänlighet",
        "score": 9.2
      }
    ],
    "tags": [
      "Flexibel",
      "Datadrivet",
      "Startup",
      "Relationsgraf"
    ],
    "pros": [
      "Exceptionellt flexibel datamodell som anpassas till unika affärsprocesser",
      "Modern och responsiv upplevelse som känns byggd för 2026",
      "AI-berikning av kontaktdata fungerar imponerande bra"
    ],
    "cons": [
      "Saknar de djupa säljautomationsfunktioner som mer mogna plattformar erbjuder",
      "Relativt litet integrationsbibliotek för ett verktyg i denna prisklass"
    ],
    "offer": {
      "title": "Attio",
      "price": "Gratis upp till 3 platser · Plus från 34 USD/plats/mån · Pro från 69 USD/plats/mån",
      "bestFor": "Startups och investeringsfirmor som vill ha ett skräddarsytt relationsbaserat CRM"
    },
    "label": "Mest flexibla strukturen",
    "score": 8.4
  },
  "folk": {
    "logo": "bg-fuchsia-600",
    "ctaName": "Folk",
    "fallbackUrl": "https://www.folk.app",
    "company": "Folk",
    "model": "Folk CRM 2026",
    "founded": 2020,
    "hq": "Paris, Frankrike",
    "useCases": [
      "Relationshantering för grundare och enskilda säljare",
      "Nätverksbaserad prospektering med AI-berikning",
      "Enkel pipeline för konsulter och frilansare",
      "Personaliserade massutskick utan komplex setup",
      "Små team utan dedikerad CRM-administratör"
    ],
    "ratingCriteria": [
      {
        "label": "AI-funktioner",
        "score": 7.8
      },
      {
        "label": "Lead scoring",
        "score": 7.6
      },
      {
        "label": "Automation",
        "score": 8
      },
      {
        "label": "Integrationer",
        "score": 8.1
      },
      {
        "label": "Pris/prestanda",
        "score": 9.1
      },
      {
        "label": "Användarvänlighet",
        "score": 9.5
      }
    ],
    "tags": [
      "Lätt",
      "Grundare",
      "Relationer",
      "Enkel"
    ],
    "pros": [
      "Enklast att komma igång med av alla verktyg i testet",
      "AI-berikning av kontakter direkt från LinkedIn fungerar smidigt",
      "Prisvärd ingångspunkt för soloentreprenörer och småteam"
    ],
    "cons": [
      "Saknar den djupa automations- och scoringkapacitet som större team behöver",
      "Skalbarhet är en reell begränsning vid snabb tillväxt"
    ],
    "offer": {
      "title": "Folk CRM",
      "price": "Standard från 20 USD/användare/mån · Premium från 40 USD/användare/mån",
      "bestFor": "Grundare, konsulter och småteam som vill ha CRM utan onödig komplexitet"
    },
    "label": "Enklast att börja med",
    "score": 8.2
  },
  "breeze-ai": {
    "logo": "bg-cyan-600",
    "ctaName": "Breeze AI",
    "fallbackUrl": "https://www.hubspot.com/products/artificial-intelligence",
    "company": "HubSpot",
    "model": "Breeze AI 2026",
    "founded": 2006,
    "hq": "Cambridge, USA",
    "useCases": [
      "AI-agenter för automatiserad prospektering",
      "Intelligent innehållsgenerering längs hela kundresan",
      "Automatiserad databerikningsprocess i CRM",
      "AI-driven kundservicehantering",
      "Sälj- och marknadsföringsteam inom HubSpot-ekosystemet"
    ],
    "ratingCriteria": [
      {
        "label": "AI-funktioner",
        "score": 9.3
      },
      {
        "label": "Lead scoring",
        "score": 8.8
      },
      {
        "label": "Automation",
        "score": 9.4
      },
      {
        "label": "Integrationer",
        "score": 9.1
      },
      {
        "label": "Pris/prestanda",
        "score": 8.4
      },
      {
        "label": "Användarvänlighet",
        "score": 9
      }
    ],
    "tags": [
      "AI-agenter",
      "HubSpot",
      "Prospektering",
      "Automatisering"
    ],
    "pros": [
      "AI-agenter för prospektering och kundservice är genuint tidssparande",
      "Djup integration i hela HubSpot-plattformen utan friktion",
      "Automatiserad databerikning håller CRM-data aktuell utan manuellt arbete"
    ],
    "cons": [
      "Kräver HubSpot som bas vilket kan vara begränsande för de utanför ekosystemet",
      "Prissättningen på de AI-tyngsta funktionerna är ännu inte helt transparent"
    ],
    "offer": {
      "title": "Breeze AI",
      "price": "Ingår i HubSpot-planer · Breeze Intelligence från 400 USD/mån · Agenter inkluderade i Pro+",
      "bestFor": "HubSpot-kunder som vill maximera AI-automatisering i sin befintliga plattform"
    },
    "label": "Bästa AI-agenter",
    "score": 9
  }
};
