/** AI-video + AI-ljud/musik review profiles — generated by
 *  scripts/seed-video-audio-reviews.ts via claude-haiku-4-5-20251001. Merged into
 *  REVIEW_KNOWN in components/templates/ReviewTemplate.tsx. Udio is
 *  intentionally absent (it has a hand-written profile). Re-run the
 *  script to refresh. */
import type { ReviewProfile } from '@/components/templates/ReviewTemplate';

export const VIDEO_AUDIO_REVIEW_KNOWN: Record<string, Partial<ReviewProfile>> = {
  "heygen": {
    "logo": "bg-purple-600",
    "ctaName": "HeyGen",
    "score": 8.7,
    "fallbackUrl": "https://www.heygen.com",
    "company": "HeyGen",
    "model": "HeyGen 3.0",
    "founded": 2023,
    "hq": "San Francisco, USA",
    "useCases": [
      "Marknadsföringsmaterial och produktdemonstrationer",
      "Kundservice och chatbot-representanter",
      "E-learning och utbildningsinnehål",
      "Sociala medier och content creation",
      "Företagskommunikation och presentationer"
    ],
    "ratingCriteria": [
      {
        "label": "Avatarrealism",
        "score": 8.8
      },
      {
        "label": "Läppsynk",
        "score": 9
      },
      {
        "label": "Språkstöd",
        "score": 8.5
      },
      {
        "label": "Röstkvalitet",
        "score": 8.7
      },
      {
        "label": "Pris och prestanda",
        "score": 8.9
      },
      {
        "label": "Användarvänlighet",
        "score": 9.1
      }
    ],
    "tags": [
      "Avatarer",
      "Företag",
      "40+ språk",
      "Talking heads"
    ],
    "pros": [
      "Realistiska avatarer",
      "Bred språkstöd",
      "Stark för säljvideo"
    ],
    "cons": [
      "Smalt användningsområde",
      "Pris hoppar snabbt"
    ],
    "offer": {
      "title": "Gratis 3 min/månad",
      "price": "Gratis · Creator 29 USD/mån",
      "bestFor": "AI-avatarer för företag"
    },
    "label": "Bäst för avatarer"
  },
  "synthesia": {
    "logo": "bg-blue-600",
    "ctaName": "Synthesia",
    "score": 8.5,
    "fallbackUrl": "https://www.synthesia.io",
    "company": "Synthesia Ltd",
    "model": "Synthesia Studio (v3)",
    "founded": 2017,
    "hq": "London, Förenade kungariket",
    "useCases": [
      "Företagsutbildning och onboarding",
      "Marknadsföring och produktlansering",
      "Kundservice och FAQ-videor",
      "Personaliserad kommunikation i stor skala",
      "Internkommunikation och HR"
    ],
    "ratingCriteria": [
      {
        "label": "Avatarrealism",
        "score": 8.7
      },
      {
        "label": "Språkstöd",
        "score": 9.2
      },
      {
        "label": "Mallar & mallbibliotek",
        "score": 8.9
      },
      {
        "label": "Enterprise-säkerhet",
        "score": 8.6
      },
      {
        "label": "Pris / prestanda",
        "score": 8.1
      },
      {
        "label": "Användarvänlighet",
        "score": 8.4
      }
    ],
    "tags": [
      "230+ avatarer",
      "140 språk",
      "L&D",
      "Enterprise"
    ],
    "pros": [
      "Branschstandard för utbildning",
      "Säker för enterprise",
      "Massiv språkbredd"
    ],
    "cons": [
      "Dyrt för småteam",
      "Mindre rörlig än konkurrenter"
    ],
    "offer": {
      "title": "36 min gratis",
      "price": "Gratis · Starter 22 USD/mån",
      "bestFor": "AI-avatarer för utbildning"
    },
    "label": "Bäst för L&D"
  },
  "invideo": {
    "logo": "bg-orange-600",
    "ctaName": "InVideo",
    "score": 8,
    "fallbackUrl": "https://invideo.io",
    "company": "InVideo",
    "model": "InVideo AI",
    "founded": 2019,
    "hq": "Bangalore, Indien",
    "useCases": [
      "sociala medier-innehål",
      "marknadsföringsvideoer",
      "produktpresentationer",
      "utbildningsvideoer",
      "företagskommunikation"
    ],
    "ratingCriteria": [
      {
        "label": "Visuell kvalitet",
        "score": 8.6
      },
      {
        "label": "Mallbibliotek",
        "score": 9.2
      },
      {
        "label": "AI-röster",
        "score": 8.4
      },
      {
        "label": "Generationstid",
        "score": 8.1
      },
      {
        "label": "Pris/prestanda",
        "score": 7.9
      },
      {
        "label": "Användarvänlighet",
        "score": 8.8
      }
    ],
    "tags": [
      "Sociala medier",
      "TikTok/Reels",
      "Mallar",
      "AI-röster"
    ],
    "pros": [
      "Snabbt social media-flöde",
      "5000+ mallar",
      "Inbyggda röster"
    ],
    "cons": [
      "Lägre kvalitet per generering",
      "Vattenstämpel i gratis"
    ],
    "offer": {
      "title": "4h video/månad gratis",
      "price": "Gratis · Plus 20 USD/mån",
      "bestFor": "Social media-video i volym"
    },
    "label": "Bäst för social media"
  },
  "luma-dream-machine": {
    "logo": "bg-cyan-600",
    "ctaName": "Luma",
    "score": 8.4,
    "fallbackUrl": "https://lumalabs.ai",
    "company": "Luma AI",
    "model": "Dream Machine",
    "founded": 2021,
    "hq": "San Francisco, USA",
    "useCases": [
      "Kortfilmer och reklamfilm",
      "Sociala medier-innehåll",
      "Produktvisualisering",
      "Konceptutveckling",
      "Animatik och storyboarding"
    ],
    "ratingCriteria": [
      {
        "label": "Visuell kvalitet",
        "score": 8.9
      },
      {
        "label": "Promptföljsamhet",
        "score": 8.3
      },
      {
        "label": "Konsistens och rörelse",
        "score": 8.6
      },
      {
        "label": "Generationstid",
        "score": 8.1
      },
      {
        "label": "Pris per generering",
        "score": 8.2
      },
      {
        "label": "Stilkontroll",
        "score": 8.4
      }
    ],
    "tags": [
      "Dream Machine",
      "Realism",
      "Image-to-video",
      "Genesis"
    ],
    "pros": [
      "Naturlig fysik och rörelse",
      "Stark image-to-video",
      "Bra pris"
    ],
    "cons": [
      "Kortare clips",
      "Mindre stilkontroll"
    ],
    "offer": {
      "title": "30 generationer gratis",
      "price": "Gratis · Standard 30 USD/mån",
      "bestFor": "Realistisk text-till-video"
    },
    "label": "Bäst för naturlig rörelse"
  },
  "adobe-firefly-video": {
    "logo": "bg-rose-600",
    "ctaName": "Firefly Video",
    "score": 7.8,
    "fallbackUrl": "https://firefly.adobe.com",
    "company": "Adobe Inc.",
    "model": "Adobe Firefly Video",
    "founded": 1982,
    "hq": "San José, USA",
    "useCases": [
      "Reklamfilm och marknadsföringsmaterial",
      "Sociala medier-innehål och korta klipp",
      "E-handelsproduktvideos",
      "Presentationer och företagskommunikation",
      "Personliga avatarer och virtuellapresentatörer"
    ],
    "ratingCriteria": [
      {
        "label": "Visuell kvalitet",
        "score": 8.6
      },
      {
        "label": "Adobe-integration",
        "score": 9.2
      },
      {
        "label": "Kommersiell trygghet",
        "score": 8.8
      },
      {
        "label": "Generationstid",
        "score": 7.4
      },
      {
        "label": "Pris/prestanda",
        "score": 7.5
      },
      {
        "label": "Användarvänlighet",
        "score": 8.3
      }
    ],
    "tags": [
      "Adobe",
      "Premiere Pro",
      "Generative Extend",
      "Kommersiellt säker"
    ],
    "pros": [
      "Inbyggt i Premiere Pro",
      "Tränad på licensierat material",
      "Bäst för pro-workflows"
    ],
    "cons": [
      "Kräver Creative Cloud",
      "Mindre kraftfull stand-alone"
    ],
    "offer": {
      "title": "Ingår i Creative Cloud",
      "price": "CC 60 USD/mån",
      "bestFor": "Adobe-användare och pro-team"
    },
    "label": "Bäst för Creative Cloud"
  },
  "kaiber": {
    "logo": "bg-amber-600",
    "ctaName": "Kaiber",
    "score": 7.5,
    "fallbackUrl": "https://kaiber.ai",
    "company": "Kaiber AI",
    "model": "Kaiber Studio",
    "founded": 2021,
    "hq": "San Francisco, USA",
    "useCases": [
      "musikvideoproduktion",
      "digitala avatarer",
      "marknadsföringsmaterial",
      "sociala medier-innehåll",
      "kreativ animering"
    ],
    "ratingCriteria": [
      {
        "label": "Konstnärlig estetik",
        "score": 8.2
      },
      {
        "label": "Beat sync",
        "score": 8.9
      },
      {
        "label": "Animationskvalitet",
        "score": 7.8
      },
      {
        "label": "Generationstid",
        "score": 7.4
      },
      {
        "label": "Pris / prestanda",
        "score": 7.1
      },
      {
        "label": "Användarvänlighet",
        "score": 7.6
      }
    ],
    "tags": [
      "Musikvideo",
      "Beat sync",
      "Animation",
      "Artister"
    ],
    "pros": [
      "Synkar till musik",
      "Konstnärlig estetik",
      "Spotify-integration"
    ],
    "cons": [
      "Smalt användningsområde",
      "Mindre realistisk"
    ],
    "offer": {
      "title": "7 dagar Pro gratis",
      "price": "Gratis · Pro 15 USD/mån",
      "bestFor": "Musiker och artister"
    },
    "label": "Bäst för musikvideor"
  },
  "mubert": {
    "logo": "bg-teal-600",
    "ctaName": "Mubert",
    "score": 8.2,
    "fallbackUrl": "https://mubert.com",
    "company": "Mubert Inc.",
    "model": "Mubert Studio",
    "founded": 2014,
    "hq": "Moskva, Ryssland",
    "useCases": [
      "Videoproduktion",
      "Podcastintro",
      "Streamingbakgrund",
      "Webbprojekt",
      "Spelljud"
    ],
    "ratingCriteria": [
      {
        "label": "Ljudkvalitet",
        "score": 8.6
      },
      {
        "label": "Stilbredd",
        "score": 9.2
      },
      {
        "label": "Royaltyfrihet",
        "score": 8.9
      },
      {
        "label": "API & integrationer",
        "score": 7.8
      },
      {
        "label": "Pris / prestanda",
        "score": 8.1
      },
      {
        "label": "Användarvänlighet",
        "score": 8.4
      }
    ],
    "tags": [
      "Streaming",
      "Royaltyfri",
      "Realtid",
      "API"
    ],
    "pros": [
      "Oändlig bakgrundsmusik",
      "Royaltyfri för creators",
      "API för utvecklare"
    ],
    "cons": [
      "Mindre konstnärlig kontroll",
      "Smal nyttighet"
    ],
    "offer": {
      "title": "Gratis för personligt bruk",
      "price": "Gratis · Creator 14 USD/mån",
      "bestFor": "Streamers och content-creators"
    },
    "label": "Bäst för bakgrundsmusik"
  },
  "aiva": {
    "logo": "bg-indigo-600",
    "ctaName": "AIVA",
    "score": 8.5,
    "fallbackUrl": "https://www.aiva.ai",
    "company": "AIVA Technologies",
    "model": "AIVA 2024",
    "founded": 2016,
    "hq": "Paris, Frankrike",
    "useCases": [
      "Film- och TV-musik",
      "Spelutveckling",
      "Podcastintro och bakgrundsmusik",
      "Reklammusik",
      "Streaming-innehål"
    ],
    "ratingCriteria": [
      {
        "label": "Ljudkvalitet",
        "score": 8.6
      },
      {
        "label": "Komposition & arrangemang",
        "score": 8.4
      },
      {
        "label": "MIDI/notexport",
        "score": 8.9
      },
      {
        "label": "Stilbredd",
        "score": 8.8
      },
      {
        "label": "Pris / prestanda",
        "score": 8.2
      },
      {
        "label": "Användarvänlighet",
        "score": 8.5
      }
    ],
    "tags": [
      "Filmmusik",
      "MIDI-export",
      "Klassiskt",
      "Spel"
    ],
    "pros": [
      "Exporterar noter och MIDI",
      "Klassisk musikteori",
      "Bra för film & spel"
    ],
    "cons": [
      "Lägre kvalitet på populärmusik",
      "Mindre intuitivt UI"
    ],
    "offer": {
      "title": "Gratisplan tillgänglig",
      "price": "Gratis · Standard 15 EUR/mån",
      "bestFor": "Film-, spel- och klassisk musik"
    },
    "label": "Bäst för kompositörer"
  },
  "soundraw": {
    "logo": "bg-emerald-600",
    "ctaName": "Soundraw",
    "score": 8,
    "fallbackUrl": "https://soundraw.io",
    "company": "Soundraw Inc.",
    "model": "Soundraw",
    "founded": 2021,
    "hq": "San Francisco, USA",
    "useCases": [
      "Videoinnehål och YouTube",
      "Podcasts och streaming",
      "Marknadsföring och annonser",
      "Sociala medier",
      "Indie-spel och appar"
    ],
    "ratingCriteria": [
      {
        "label": "Ljudkvalitet",
        "score": 8.6
      },
      {
        "label": "Anpassningsbarhet",
        "score": 9.1
      },
      {
        "label": "Stems-export",
        "score": 7.8
      },
      {
        "label": "Royaltyfrihet",
        "score": 9
      },
      {
        "label": "Pris / prestanda",
        "score": 8.2
      },
      {
        "label": "Användarvänlighet",
        "score": 8.5
      }
    ],
    "tags": [
      "Royaltyfri",
      "Anpassningsbar",
      "Stems",
      "Mood-baserad"
    ],
    "pros": [
      "Granulär anpassning per spår",
      "Stems-export",
      "Royaltyfri kommersiellt"
    ],
    "cons": [
      "Begränsad stilbredd",
      "Vattenstämpel i gratis"
    ],
    "offer": {
      "title": "Gratis preview",
      "price": "Creator 17 USD/mån",
      "bestFor": "YouTube-creators och reklam"
    },
    "label": "Bäst för YouTubers"
  },
  "boomy": {
    "logo": "bg-fuchsia-600",
    "ctaName": "Boomy",
    "score": 7.4,
    "fallbackUrl": "https://boomy.com",
    "company": "Boomy Inc.",
    "model": "Boomy AI Music Generator",
    "founded": 2018,
    "hq": "Los Angeles, USA",
    "useCases": [
      "Skapa royalty-fri bakgrundsmusik för videos",
      "Generera musik för sociala medier och innehåll",
      "Producera jingles och reklaminspelningar",
      "Komponera musik för indie-spel och appar",
      "Få musikrätter utan juridisk komplexitet"
    ],
    "ratingCriteria": [
      {
        "label": "Ljudkvalitet",
        "score": 7.2
      },
      {
        "label": "Användarvänlighet",
        "score": 8.6
      },
      {
        "label": "Streaming och publicering",
        "score": 8.4
      },
      {
        "label": "Genereringshastighet",
        "score": 8.8
      },
      {
        "label": "Pris och värde",
        "score": 6.9
      },
      {
        "label": "Musikvarietet och kontroll",
        "score": 7.5
      }
    ],
    "tags": [
      "1-klick",
      "Spotify-release",
      "Royaltyandel",
      "Enkelt"
    ],
    "pros": [
      "Snabbast att komma igång",
      "Publicera till streaming-tjänster",
      "Tjäna royalty"
    ],
    "cons": [
      "Begränsad kontroll",
      "Lägre produktionskvalitet"
    ],
    "offer": {
      "title": "25 låtar gratis",
      "price": "Gratis · Creator 10 USD/mån",
      "bestFor": "Snabb publicering till streaming"
    },
    "label": "Bäst för nybörjare"
  },
  "splice": {
    "logo": "bg-orange-600",
    "ctaName": "Splice",
    "score": 8.3,
    "fallbackUrl": "https://splice.com",
    "company": "Splice",
    "model": "Splice Cloud Studio",
    "founded": 2013,
    "hq": "New York, USA",
    "useCases": [
      "musikproduktion",
      "beat-making",
      "sampling",
      "vokalbearbetning",
      "sound-design"
    ],
    "ratingCriteria": [
      {
        "label": "Sample-bibliotek",
        "score": 9.1
      },
      {
        "label": "AI-sökning",
        "score": 8.9
      },
      {
        "label": "Stems-separation",
        "score": 8.2
      },
      {
        "label": "Ljudkvalitet",
        "score": 8.7
      },
      {
        "label": "Pris / prestanda",
        "score": 7.9
      },
      {
        "label": "Användarvänlighet",
        "score": 8.4
      }
    ],
    "tags": [
      "Samples",
      "AI-sökning",
      "Stems-separation",
      "Producenter"
    ],
    "pros": [
      "Miljontals samples",
      "AI hittar matchande loops",
      "Producent-favorit"
    ],
    "cons": [
      "Kräver DAW-kunskap",
      "Inte gen-AI för hela låtar"
    ],
    "offer": {
      "title": "Sample-bibliotek från 8 USD/mån",
      "price": "Creator 8 USD/mån",
      "bestFor": "Musikproducenter"
    },
    "label": "Bäst för producenter"
  },
  "lalal-ai": {
    "logo": "bg-sky-600",
    "ctaName": "Lalal.ai",
    "score": 8.7,
    "fallbackUrl": "https://www.lalal.ai",
    "company": "Lalal.ai",
    "model": "Lalal.ai v2",
    "founded": 2021,
    "hq": "Kiev, Ukraina",
    "useCases": [
      "Musikproduktion och mastering",
      "Podcast- och voiceoverredigering",
      "DJ-mixer och remix",
      "Instrumental- och vokalextrahering",
      "Arkivering och restaurering av äldre inspelningar"
    ],
    "ratingCriteria": [
      {
        "label": "Separationskvalitet",
        "score": 9.1
      },
      {
        "label": "Antal stems",
        "score": 8.5
      },
      {
        "label": "Hastighet",
        "score": 8.8
      },
      {
        "label": "Ljudbevarande",
        "score": 8.9
      },
      {
        "label": "Pris per minut",
        "score": 8.4
      },
      {
        "label": "Användarvänlighet",
        "score": 8.5
      }
    ],
    "tags": [
      "Stems-separation",
      "Vocal isolation",
      "Karaoke",
      "API"
    ],
    "pros": [
      "Marknadsledande separation",
      "Snabb",
      "Stöd för 10+ stems"
    ],
    "cons": [
      "Smalt användningsområde",
      "Begränsade minuter i gratis"
    ],
    "offer": {
      "title": "10 min gratis/månad",
      "price": "Gratis · Lite 9 USD/mån",
      "bestFor": "Karaoke, remix och stems"
    },
    "label": "Bäst för stems-separation"
  },
  "adobe-podcast": {
    "logo": "bg-rose-700",
    "ctaName": "Adobe Podcast",
    "score": 8.6,
    "fallbackUrl": "https://podcast.adobe.com",
    "company": "Adobe Inc.",
    "model": "Adobe Podcast",
    "founded": 2021,
    "hq": "San José, USA",
    "useCases": [
      "podcastproduktion",
      "intervjuinspelning",
      "ljudredigering",
      "röstöver",
      "musikproduktion"
    ],
    "ratingCriteria": [
      {
        "label": "Röstförbättring",
        "score": 8.8
      },
      {
        "label": "Brusreducering",
        "score": 9
      },
      {
        "label": "Ljudkvalitet",
        "score": 8.5
      },
      {
        "label": "Hastighet",
        "score": 8.7
      },
      {
        "label": "Pris",
        "score": 7.2
      },
      {
        "label": "Användarvänlighet",
        "score": 9.1
      }
    ],
    "tags": [
      "AI Enhance",
      "Brusreducering",
      "Gratis",
      "Webb"
    ],
    "pros": [
      "Studio-kvalitet i webbläsaren",
      "Helt gratis",
      "Adobe-kvalitet"
    ],
    "cons": [
      "Endast röstförbättring",
      "Köbaserat vid hög belastning"
    ],
    "offer": {
      "title": "Helt gratis",
      "price": "Gratis · ingår i Creative Cloud",
      "bestFor": "Podcasters och röstinspelning"
    },
    "label": "Bäst gratis-verktyget"
  }
};
