/**
 * 20 YrkeTool entries for the two new yrkesroller "Designer" and
 * "Fotograf & Videoskapare" (depth-4 pages under /ai-verktyg/foretag/
 * yrke/). Each tool is explicitly mapped to its natural subcategory —
 * no auto-expansion across subs (different from yrke-tools-extended.ts
 * which replicates 3× for the juridik/kundservice/rekrytering pattern).
 *
 * Slug suffixes (-design, -ux, -dbild, -dvid, -bredig, -vklipp, -fbild,
 * -ljud) keep slugs unique across yrkesroller — Adobe Firefly and
 * Runway appear in both yrkesroller for different reasons.
 *
 * Imported by lib/yrke-tools.ts and spread into YRKE_TOOLS so the
 * standard seed-yrke-reviews.ts + KNOWN/REVIEW_KNOWN maps pick them
 * up automatically.
 */
import type { YrkeTool } from './yrke-tools';

export const DESIGNER_FOTOGRAF_TOOLS: YrkeTool[] = [
  /* ── DESIGNER · Grafisk design ─────────────────────────────── */
  {
    slug: 'canva-ai-design', parent: 'grafisk-design',
    brand: 'Canva AI (Magic Studio)', company: 'Canva', founded: 2013, hq: 'Sydney, Australien',
    score: 8.6, fallbackUrl: 'https://www.canva.com/ai',
    title: 'Canva AI för grafisk design — Recension 2026',
    oneliner: 'Canvas inbyggda AI för text-till-bild, Magic Edit och brand-genererare.',
    features: ['Magic Design från prompt', 'Brand Kit-låsta färger/typsnitt', 'Bakgrundsborttagning', 'Magic Edit + Resize'],
    pros: ['Sömlös för icke-designers', 'Bästa mall-bibliotek', 'Solid svensk språkstöd'],
    cons: ['Begränsad kreativ frihet jämfört med Photoshop', 'Avancerade features kräver Pro'],
    pricing: 'Free 50 generationer/mån; Pro 12 USD/mån (500/mån); Teams 27.',
    bestFor: 'Småföretagare, marknadsförare och icke-designers',
    offer: { title: '30 dagar Pro-trial', price: 'Free / Pro 12 USD/mån' },
    tags: ['Canva', 'Mallar', 'Brand Kit', 'Icke-designer'],
    useCases: ['Sociala medier', 'Presentationer', 'Posters', 'Brand-grafik', 'Newsletter-banners'],
    label: 'Redaktionens val', logo: 'bg-sky-600',
  },
  {
    slug: 'adobe-firefly-design', parent: 'grafisk-design',
    brand: 'Adobe Firefly', company: 'Adobe', founded: 1982, hq: 'San Jose, USA',
    score: 9.0, fallbackUrl: 'https://www.adobe.com/products/firefly.html',
    title: 'Adobe Firefly för grafisk design — Recension 2026',
    oneliner: 'Kommersiellt säker AI tränad på Adobe Stock — integrerad i Photoshop, Illustrator och Express.',
    features: ['Generative Fill i Photoshop', 'Text-to-vector i Illustrator', 'Brand-templates', 'IP-fri output'],
    pros: ['Juridiskt säker output (Adobe garanterar)', 'Native i Creative Cloud', 'Stark typografisk kontroll'],
    cons: ['Kräver Adobe-prenumeration för bästa upplevelse', 'Mindre stilistisk variation än Midjourney'],
    pricing: 'Free 25 credits/mån; Premium 5 USD/mån; ingår i Creative Cloud (60 USD/mån).',
    bestFor: 'Designers som redan kör Adobe-stack',
    offer: { title: 'Ingår i CC', price: 'Free / Premium 5 USD/mån' },
    tags: ['Kommersiellt säker', 'Photoshop', 'Illustrator', 'Vector'],
    useCases: ['Brand-design', 'Print-grafik', 'Photoshop-retusch', 'Illustrator-vectors', 'Stock-ersättning'],
    label: 'Bäst för Adobe-stack', logo: 'bg-red-700',
  },
  {
    slug: 'looka-design', parent: 'grafisk-design',
    brand: 'Looka', company: 'Looka Inc.', founded: 2016, hq: 'Toronto, Kanada',
    score: 7.9, fallbackUrl: 'https://looka.com',
    title: 'Looka — AI-logotypgenerator Recension 2026',
    oneliner: 'AI-driven logotypgenerator + brand kit-bygge på minuter — för startups och småföretagare.',
    features: ['Brand Kit-generering', 'Logo + favicon + social-paket', 'Färgpalett + typsnitt-förslag', 'Reseller-licens'],
    pros: ['Snabbaste vägen från idé till logo', 'Komplett brand-paket', 'Engångsköp finns'],
    cons: ['Begränsad kreativ frihet', 'Logos kan kännas generiska'],
    pricing: 'Logo Pack 20 USD engångs; Brand Kit 65 USD; Subscriptions från 8 USD/mån.',
    bestFor: 'Solopreneurer och startups som behöver snabb visuell identitet',
    offer: { title: 'Engångsköp möjligt', price: 'Från 20 USD engångs' },
    tags: ['Logo', 'Brand Kit', 'Startups', 'Engångsköp'],
    useCases: ['Startup-logo', 'Visitkort', 'Brand-paket', 'Re-brand', 'Domännamn-test'],
    label: 'Bäst för snabb logo', logo: 'bg-amber-600',
  },

  /* ── DESIGNER · UI/UX ──────────────────────────────────────── */
  {
    slug: 'figma-ai-ux', parent: 'ui-ux',
    brand: 'Figma AI', company: 'Figma (Adobe)', founded: 2012, hq: 'San Francisco, USA',
    score: 9.3, fallbackUrl: 'https://www.figma.com/ai',
    title: 'Figma AI — Recension 2026',
    oneliner: 'AI-funktioner inbäddade i Figma — från First Draft till Auto-Layout-prompts.',
    features: ['First Draft från prompt', 'AI-omformulering av copy', 'Auto-layout-förslag', 'Visual search i bibliotek'],
    pros: ['Direkt i designers favoritverktyg', 'Stark prompt-följsamhet', 'Sömlös med Dev Mode'],
    cons: ['Premium-features krävs för full AI', 'Vissa funktioner i beta'],
    pricing: 'Free Starter; Professional 15 USD/seat/mån; Organization 45.',
    bestFor: 'Produktdesigners och UX-team',
    offer: { title: 'Free Starter-plan', price: 'Free / Pro 15 USD/seat/mån' },
    tags: ['Figma', 'First Draft', 'Auto-Layout', 'Produkt-design'],
    useCases: ['Wireframes', 'Komponentförslag', 'Auto-layout', 'Dev-handoff', 'Design-system'],
    label: 'Redaktionens val', logo: 'bg-violet-700',
  },
  {
    slug: 'galileo-ai-ux', parent: 'ui-ux',
    brand: 'Galileo AI', company: 'Galileo', founded: 2022, hq: 'San Francisco, USA',
    score: 8.5, fallbackUrl: 'https://www.usegalileo.ai',
    title: 'Galileo AI — Text-to-UI Recension 2026',
    oneliner: 'Genererar produktiona UI-skärmar från textbeskrivning — exporterar direkt till Figma.',
    features: ['Text-to-UI på sekunder', 'Figma-export', 'Komponentbibliotek inbyggt', 'Mobile-first templates'],
    pros: ['Bästa text-to-UI på marknaden', 'Snabbar wireframe-process drastiskt', 'Bra för pitch-mockups'],
    cons: ['Begränsad customization efter generering', 'Pris hoppar vid skala'],
    pricing: 'Free trial; Pro 19 USD/mån; Teams 30/user/mån.',
    bestFor: 'Designteam som behöver snabba mockups',
    offer: { title: 'Free trial', price: 'Pro 19 USD/mån' },
    tags: ['Text-to-UI', 'Mockups', 'Figma-export', 'Wireframes'],
    useCases: ['Pitch-mockups', 'Wireframes', 'Onboarding-screens', 'Design-system', 'Klient-presentationer'],
    label: 'Bäst för mockups', logo: 'bg-indigo-700',
  },
  {
    slug: 'uizard-ux', parent: 'ui-ux',
    brand: 'Uizard', company: 'Uizard Technologies', founded: 2018, hq: 'Köpenhamn, Danmark',
    score: 8.2, fallbackUrl: 'https://uizard.io',
    title: 'Uizard — Sketch-to-Design Recension 2026',
    oneliner: 'Förvandlar pappersskisser och screenshots till digitala UI-designs via AI.',
    features: ['Hand-drawn-to-UI', 'Screenshot-to-design', 'Theme generator', 'Code-export (begränsad)'],
    pros: ['Unik sketch-to-UI-funktionalitet', 'Danskt bolag — EU-baserat', 'Bra för ideationsfasen'],
    cons: ['Output behöver finputs', 'Mindre community än Figma'],
    pricing: 'Free 3 projekt; Pro 19 USD/mån; Business 39.',
    bestFor: 'Designers som börjar med pappersskisser',
    offer: { title: 'Free 3 projekt', price: 'Pro 19 USD/mån' },
    tags: ['Sketch-to-UI', 'EU-baserat', 'Ideation', 'Theme generator'],
    useCases: ['Pappersskiss-digitalisering', 'Screenshot-redesign', 'Tema-generering', 'Ideationssession', 'Pitch-prototyp'],
    label: 'Bäst sketch-to-UI', logo: 'bg-emerald-700',
  },
  {
    slug: 'framer-ai-ux', parent: 'ui-ux',
    brand: 'Framer AI', company: 'Framer B.V.', founded: 2013, hq: 'Amsterdam, Nederländerna',
    score: 8.7, fallbackUrl: 'https://www.framer.com/ai',
    title: 'Framer AI — Text-to-Site Recension 2026',
    oneliner: 'Genererar fullständiga, responsiva websidor från textbeskrivning — publiceras direkt.',
    features: ['Text-to-Site i en prompt', 'Inbyggd CMS', 'Animation utan kod', 'Custom domain'],
    pros: ['Snabbaste prompt-till-publicerad-site', 'Inbyggt hosting', 'Bra animationsstöd'],
    cons: ['Mindre kontroll än Webflow', 'Lite begränsad för komplexa webbappar'],
    pricing: 'Free med Framer-subdomän; Mini 5 USD/mån; Pro 15.',
    bestFor: 'Designers som behöver portfolios eller landningssidor snabbt',
    offer: { title: 'Free med subdomän', price: 'Pro 15 USD/mån' },
    tags: ['Text-to-site', 'Hosting', 'Animation', 'CMS'],
    useCases: ['Portfolios', 'Landningssidor', 'Pitch-sites', 'Klient-presentationer', 'Event-sidor'],
    label: 'Bäst för publicering', logo: 'bg-blue-700',
  },

  /* ── DESIGNER · Bildgenerering (designer-vinkel) ───────────── */
  {
    slug: 'midjourney-design', parent: 'designer-bildgenerering',
    brand: 'Midjourney', company: 'Midjourney Inc.', founded: 2022, hq: 'San Francisco, USA',
    score: 9.4, fallbackUrl: 'https://www.midjourney.com',
    title: 'Midjourney för designers — Recension 2026',
    oneliner: 'Bästa estetiska kvaliteten — designers använder den för mood boards, koncept och hero-bilder.',
    features: ['v7-modell med fotorealism', 'Style references (sref)', 'Moodboards', 'Vary Region för iterationer'],
    pros: ['Vackrast output by default', 'Stark stil-konsistens med sref', 'Stort bibliotek av community-stilar'],
    cons: ['Discord-/web-only UI', 'Ingen direkt Figma-integration'],
    pricing: 'Basic 10 USD/mån (200 bilder); Standard 30; Pro 60; Mega 120.',
    bestFor: 'Designers som vill ha estetisk topp-kvalitet',
    offer: { title: '10 USD billigaste plan', price: 'Från 10 USD/mån' },
    tags: ['v7', 'Moodboards', 'sref', 'Estetik'],
    useCases: ['Hero-bilder', 'Moodboards', 'Koncept-art', 'Pitch-visuals', 'Stil-explorationer'],
    label: 'Bäst för estetisk koncept-art', logo: 'bg-zinc-900',
  },
  {
    slug: 'khroma-design', parent: 'designer-bildgenerering',
    brand: 'Khroma', company: 'Khroma', founded: 2020, hq: 'London, UK',
    score: 7.6, fallbackUrl: 'https://khroma.co',
    title: 'Khroma — AI-färgpaletter Recension 2026',
    oneliner: 'AI som lär sig dina färgpreferenser och genererar oändliga palett-förslag.',
    features: ['Lär sig från dina färg-val', 'Genererar palett-par', 'Typografi + gradient-förslag', 'Spara favoriter'],
    pros: ['Smart palett-rekommendation', 'Bra för designer som fastnat i färg-block', 'Engångs-träning per användare'],
    cons: ['Bara färger — inga andra design-features', 'Mindre community'],
    pricing: 'Helt gratis (alfa).',
    bestFor: 'Designers som vill upptäcka nya färgpaletter',
    offer: { title: 'Helt gratis', price: 'Gratis' },
    tags: ['Färgpaletter', 'Gratis', 'Typografi', 'Gradients'],
    useCases: ['Färgpaletter', 'Brand-färger', 'Gradients', 'Typografikombos', 'Inspirationsverktyg'],
    label: 'Bäst för färgpaletter', logo: 'bg-fuchsia-600',
  },

  /* ── DESIGNER · Videoredigering ────────────────────────────── */
  {
    slug: 'runway-design', parent: 'videoredigering',
    brand: 'Runway', company: 'Runway AI', founded: 2018, hq: 'New York, USA',
    score: 9.0, fallbackUrl: 'https://runwayml.com',
    title: 'Runway för designers — Recension 2026',
    oneliner: 'Gen-3-modellen för text-to-video plus en svit Magic Tools för designers.',
    features: ['Gen-3 Alpha text-to-video', 'Magic Tools (motion brush, frame interp)', 'Image-to-video', 'Real-time canvas'],
    pros: ['Designer-vänliga AI-video-features', 'Bra för moodboard-rörelse', 'Aktiv produktutveckling'],
    cons: ['Krediter förbrukas snabbt vid 1080p', 'Pris hoppar vid skala'],
    pricing: 'Free 125 credits; Standard 15 USD/mån; Pro 35; Unlimited 95.',
    bestFor: 'Designers som behöver kort video-content',
    offer: { title: 'Free 125 credits', price: 'Standard 15 USD/mån' },
    tags: ['Gen-3', 'Magic Tools', 'Motion brush', 'Designer'],
    useCases: ['Hero-video', 'Brand-rörelse', 'Animerade illustrationer', 'Pitch-videos', 'Social shorts'],
    label: 'Bäst för design-video', logo: 'bg-cyan-700',
  },

  /* ── FOTOGRAF · Bildredigering ─────────────────────────────── */
  {
    slug: 'luminar-neo-bredig', parent: 'bildredigering',
    brand: 'Luminar Neo AI', company: 'Skylum', founded: 2008, hq: 'Bellevue, USA',
    score: 9.1, fallbackUrl: 'https://skylum.com/luminar',
    title: 'Luminar Neo AI — Recension 2026',
    oneliner: 'AI-driven foto-editor med scene-detection, sky replacement och structure-AI.',
    features: ['Sky AI / Sun Rays / Atmosphere AI', 'Structure AI för landskap', 'Portrait Bokeh AI', 'Plugin för Photoshop/Lightroom'],
    pros: ['Bästa AI-himlen på marknaden', 'En-klick-redigeringar för landskap', 'Engångsköp finns'],
    cons: ['Inte ersättare för Lightroom — komplement', 'Tunga AI-extensions extra'],
    pricing: 'Engångsköp 99 USD; Pro 119 USD/år; Extensions 299 USD.',
    bestFor: 'Landskaps- och bröllops-fotografer',
    offer: { title: '30 dagar gratis trial', price: '99 USD engångs' },
    tags: ['Sky AI', 'Landskap', 'Engångsköp', 'Photoshop-plugin'],
    useCases: ['Landskapsfoto', 'Bröllopsfoto', 'Sky replacement', 'Portrait-retusch', 'Komposit'],
    label: 'Redaktionens val', logo: 'bg-indigo-700',
  },
  {
    slug: 'topaz-photo-bredig', parent: 'bildredigering',
    brand: 'Topaz Photo AI', company: 'Topaz Labs', founded: 2005, hq: 'Dallas, USA',
    score: 9.2, fallbackUrl: 'https://www.topazlabs.com/topaz-photo-ai',
    title: 'Topaz Photo AI — Recension 2026',
    oneliner: 'Branschstandard för AI-driven upscaling, denoising och skärpning.',
    features: ['Upscale upp till 6x', 'Denoise med subjekt-detection', 'Sharpen för out-of-focus', 'Face Recovery'],
    pros: ['Marknadsledande upscale-kvalitet', 'Engångsköp = ingen prenumeration', 'Standalone + plugin'],
    cons: ['Pricey för engångsköp', 'GPU-intensiv'],
    pricing: 'Engångsköp 199 USD inkl. 1 års uppdateringar; sedan 99 USD/år.',
    bestFor: 'Yrkesfotografer som behöver maximal bildkvalitet',
    offer: { title: '30 dagar gratis trial', price: '199 USD engångs' },
    tags: ['Upscale', 'Denoise', 'Engångsköp', 'Photoshop-plugin'],
    useCases: ['Upscale gamla foton', 'Bröllopsbilder', 'Tryckkvalitet', 'Stock-foto-prep', 'Arkiv-restaurering'],
    label: 'Bäst för upscale', logo: 'bg-slate-700',
  },
  {
    slug: 'removebg-bredig', parent: 'bildredigering',
    brand: 'Remove.bg', company: 'Kaleido AI', founded: 2018, hq: 'Wien, Österrike',
    score: 8.6, fallbackUrl: 'https://www.remove.bg',
    title: 'Remove.bg — AI-bakgrundsborttagning Recension 2026',
    oneliner: 'Marknadsledande för automatisk bakgrundsborttagning — API, web och desktop-app.',
    features: ['Automatisk bakgrundsborttagning', 'Batch-processing', 'API för utvecklare', 'Photoshop/Sketch-plugin'],
    pros: ['Bästa bakgrundsborttagning på marknaden', 'Snabb API', 'Hairline-kvalitet på hår och päls'],
    cons: ['Smalt användningsområde', 'Pricey vid hög volym'],
    pricing: 'Free preview-kvalitet; HD-bilder 0.20 USD/st eller subscription från 9 USD/mån.',
    bestFor: 'E-handlare och produktfotografer',
    offer: { title: 'Free preview-bilder', price: 'Subscription från 9 USD/mån' },
    tags: ['Bakgrund', 'API', 'Batch', 'E-handel'],
    useCases: ['Produktbilder', 'Porträtt-cutout', 'Marknadsföring', 'Batch-processing', 'E-handel'],
    label: 'Bäst bakgrundsborttagning', logo: 'bg-emerald-600',
  },

  /* ── FOTOGRAF · Videoklippning ─────────────────────────────── */
  {
    slug: 'capcut-ai-vklipp', parent: 'videoklippning',
    brand: 'CapCut AI', company: 'ByteDance', founded: 2019, hq: 'Singapore',
    score: 8.9, fallbackUrl: 'https://www.capcut.com',
    title: 'CapCut AI — Videoredigering Recension 2026',
    oneliner: 'Gratis videoredigerare med inbyggd AI — auto-captions, talking head-features och scen-redigering.',
    features: ['Auto-captions på 60+ språk', 'AI-bakgrundsborttagning', 'Magic Cut för långa intervjuer', 'Cross-device sync'],
    pros: ['Helt gratis huvudfunktionalitet', 'Mobil + desktop sync', 'Snabb auto-redigering'],
    cons: ['Tillhör ByteDance (TikTok-moderbolag)', 'Sponsrade features kan dyka upp'],
    pricing: 'Free huvudversion; Pro 8 USD/mån för premium-effekter.',
    bestFor: 'Content-creators för TikTok, Reels och Shorts',
    offer: { title: 'Helt gratis', price: 'Pro 8 USD/mån' },
    tags: ['Auto-captions', 'Gratis', 'Mobil', 'TikTok-flow'],
    useCases: ['TikTok-content', 'Reels', 'YouTube Shorts', 'Reaktionsvideos', 'Intervjuredigering'],
    label: 'Redaktionens val gratis', logo: 'bg-zinc-900',
  },
  {
    slug: 'canva-video-vklipp', parent: 'videoklippning',
    brand: 'Canva Video', company: 'Canva', founded: 2013, hq: 'Sydney, Australien',
    score: 8.3, fallbackUrl: 'https://www.canva.com/video-editor',
    title: 'Canva Video Editor AI — Recension 2026',
    oneliner: 'Canvas videoeditor med AI-redigering, auto-captions och brand-genererad video.',
    features: ['AI auto-captions', 'Brand Kit i video', 'Magic Switch (format-konverter)', 'Stock-bibliotek'],
    pros: ['Sömlös för marknadsförare', 'Stark mallibibliotek', 'Brand-locked färger/typsnitt'],
    cons: ['Begränsad för avancerad redigering', 'Pro krävs för längre videoklipp'],
    pricing: 'Free 60 sek; Pro 12 USD/mån för längre + Magic Switch.',
    bestFor: 'Marknadsteam och småföretagare',
    offer: { title: 'Free 60-sek videoklipp', price: 'Pro 12 USD/mån' },
    tags: ['Canva', 'Brand Kit', 'Mallar', 'Marknadsföring'],
    useCases: ['Social media-video', 'Reklamfilmer', 'Tutorials', 'Annonser', 'Pitch-video'],
    label: 'Bäst för marknadsföring', logo: 'bg-sky-600',
  },

  /* ── FOTOGRAF · Bildgenerering (foto-vinkel) ───────────────── */
  {
    slug: 'firefly-fbild', parent: 'foto-bildgenerering',
    brand: 'Adobe Firefly', company: 'Adobe', founded: 1982, hq: 'San Jose, USA',
    score: 8.9, fallbackUrl: 'https://www.adobe.com/products/firefly.html',
    title: 'Adobe Firefly för fotografer — Recension 2026',
    oneliner: 'AI-bildgenerering integrerad i Photoshop — Generative Fill för foto-retouch.',
    features: ['Generative Fill i Photoshop', 'Generative Expand', 'Reference Image (sref)', 'Kommersiellt säker output'],
    pros: ['Direkt i Photoshop-flödet', 'Juridiskt säker för kommersiellt bruk', 'Bästa text-i-bild för foton'],
    cons: ['Mindre stilistisk variation än Midjourney', 'Kreditgräns på alla planer'],
    pricing: 'Free 25 credits/mån; Premium 5 USD/mån; CC-plan 60 USD/mån.',
    bestFor: 'Fotografer som vill expandera/redigera foton med AI',
    offer: { title: 'Ingår i Creative Cloud', price: 'Free / Premium 5 USD/mån' },
    tags: ['Photoshop', 'Generative Fill', 'Kommersiell', 'Foto-retouch'],
    useCases: ['Foto-utvidgning', 'Bakgrundsbyte', 'Object-removal', 'Stock-ersättning', 'Komposit'],
    label: 'Redaktionens val foto-AI', logo: 'bg-red-700',
  },
  {
    slug: 'runway-fbild', parent: 'foto-bildgenerering',
    brand: 'Runway Gen-3', company: 'Runway AI', founded: 2018, hq: 'New York, USA',
    score: 9.0, fallbackUrl: 'https://runwayml.com',
    title: 'Runway Gen-3 för fotografer — Recension 2026',
    oneliner: 'Image-to-video och Gen-3 för fotografer som vill animera stillbilder.',
    features: ['Image-to-video Gen-3', 'Camera control', 'Motion brush på stillbilder', 'Frame interpolation'],
    pros: ['Animera fotografier till levande bilder', 'Bra cinematisk kontroll', 'Hög upplösning'],
    cons: ['Krediter försvinner snabbt', 'Längre klipp kräver Pro'],
    pricing: 'Free 125 credits; Standard 15 USD/mån; Pro 35; Unlimited 95.',
    bestFor: 'Fotografer som vill skapa cinemagraphs eller stillbilds-rörelse',
    offer: { title: 'Free 125 credits', price: 'Standard 15 USD/mån' },
    tags: ['Gen-3', 'Image-to-video', 'Cinemagraphs', 'Motion'],
    useCases: ['Cinemagraphs', 'Foto-till-video', 'Annonser', 'Konceptvideos', 'Stillbildsrörelse'],
    label: 'Bäst foto-till-video', logo: 'bg-cyan-700',
  },
  {
    slug: 'pika-fbild', parent: 'foto-bildgenerering',
    brand: 'Pika Labs', company: 'Pika Labs', founded: 2023, hq: 'San Francisco, USA',
    score: 8.5, fallbackUrl: 'https://pika.art',
    title: 'Pika Labs — Recension 2026',
    oneliner: 'Snabb AI-video från text eller stillbilder — populär bland creators.',
    features: ['Text-to-video + Image-to-video', 'Modifiera klipp med prompt', 'Sound effects-generering', 'Sociala templates'],
    pros: ['Snabbaste generering', 'Bra för shorts/Reels', 'Inbyggda templates'],
    cons: ['Lägre upplösning än Runway Pro', 'Vattenstämpel på gratis-plan'],
    pricing: 'Free 250 credits/månad; Standard 10 USD/mån; Pro 35.',
    bestFor: 'Creators som behöver snabb AI-video',
    offer: { title: 'Free 250 credits', price: 'Standard 10 USD/mån' },
    tags: ['Snabb', 'Creator', 'Templates', 'Shorts'],
    useCases: ['TikTok-content', 'Reels', 'Snabba mockups', 'Sociala annonser', 'Idégenerering'],
    label: 'Snabbast generering', logo: 'bg-pink-700',
  },

  /* ── FOTOGRAF · Ljudsättning ───────────────────────────────── */
  {
    slug: 'descript-ljud', parent: 'ljudsattning',
    brand: 'Descript', company: 'Descript', founded: 2017, hq: 'San Francisco, USA',
    score: 9.0, fallbackUrl: 'https://www.descript.com',
    title: 'Descript — Recension 2026',
    oneliner: 'Ljud- och videoredigering via transkription — redigera ljud genom att redigera text.',
    features: ['Edit-by-text', 'Studio Sound (AI denoising)', 'Overdub (AI voice cloning)', 'Inbyggd screen recording'],
    pros: ['Revolutionerande edit-by-text', 'Bästa AI-denoising', 'All-in-one för podcast/video'],
    cons: ['Brant inlärningskurva första veckan', 'Pro krävs för Overdub'],
    pricing: 'Free 1 timme/månad; Creator 12 USD/mån; Pro 24.',
    bestFor: 'Podcasters och YouTube-creators',
    offer: { title: 'Free 1 tim/mån', price: 'Creator 12 USD/mån' },
    tags: ['Podcast', 'Edit-by-text', 'Voice cloning', 'Studio Sound'],
    useCases: ['Podcast-redigering', 'Intervjuer', 'Voice-over', 'Talking head-video', 'Screen recording'],
    label: 'Redaktionens val', logo: 'bg-purple-700',
  },
  {
    slug: 'krisp-ljud', parent: 'ljudsattning',
    brand: 'Krisp', company: 'Krisp Technologies', founded: 2017, hq: 'San Francisco, USA',
    score: 8.7, fallbackUrl: 'https://krisp.ai',
    title: 'Krisp — AI-brusreducering Recension 2026',
    oneliner: 'Realtidsbrusreducering för möten, podcasts och inspelningar — körs systemövergripande.',
    features: ['Realtids brusreducering', 'Eko-cancellering', 'Möten-AI (transcription + sammanfattning)', 'Plug-and-play för alla appar'],
    pros: ['Bästa realtidsbrus på marknaden', 'Funkar i alla appar', 'Free-tier räcker för många'],
    cons: ['Mindre relevant för post-produktion', 'Använder CPU-resurser'],
    pricing: 'Free 60 min/dag; Pro 8 USD/mån (obegränsat); Business 14.',
    bestFor: 'Distansarbete och remote-podcasters',
    offer: { title: 'Free 60 min/dag', price: 'Pro 8 USD/mån' },
    tags: ['Brusreducering', 'Realtid', 'Möten', 'AI-transkription'],
    useCases: ['Möten i bullriga miljöer', 'Remote-podcasts', 'Streaming', 'Voice-over', 'Call centers'],
    label: 'Bäst för möten', logo: 'bg-orange-600',
  },
];
