/**
 * 30 base tool profiles for juridik, kundservice and rekrytering, expanded
 * to 90 YrkeTool entries (one per (tool × subcategory) within each yrkesroll).
 *
 * Each base tool is replicated under all 3 subcategories of its yrkesroll
 * because the user spec calls for 10 verktyg per hub-sida and we have 10
 * tools per yrkesroll. Slugs get a short subcategory suffix so they stay
 * unique across the articles table. parent_slug matches the subcategory.
 *
 * Imported from lib/yrke-tools.ts and spread into YRKE_TOOLS at module
 * load, so YRKE_HUB_KNOWN / YRKE_REVIEW_KNOWN auto-pick up the 90 entries.
 */

import type { YrkeTool, YrkeParent } from './yrke-tools';

type Yrkesroll = 'juridik' | 'kundservice' | 'rekrytering';

type BaseTool = Omit<YrkeTool, 'slug' | 'parent' | 'title'> & {
  baseSlug: string;
  yrkesroll: Yrkesroll;
};

type SubcatRef = { slug: YrkeParent; suffix: string; label: string };

const SUBCATS_BY_ROLE: Record<Yrkesroll, SubcatRef[]> = {
  juridik: [
    { slug: 'avtalsgranskning', suffix: 'avtal', label: 'avtalsgranskning' },
    { slug: 'due-diligence',    suffix: 'dd',    label: 'due diligence' },
    { slug: 'rattsutredningar', suffix: 'ratts', label: 'rättsutredningar' },
  ],
  kundservice: [
    { slug: 'chatbot',     suffix: 'chatbot', label: 'chatbot-driven kundservice' },
    { slug: 'epost-svar',  suffix: 'epost',   label: 'AI-assisterade e-postsvar' },
    { slug: 'rost-ai',     suffix: 'rost',    label: 'röst-AI och voicebots' },
  ],
  rekrytering: [
    { slug: 'cv-screening',       suffix: 'cv',       label: 'CV-screening' },
    { slug: 'jobbannonser',       suffix: 'annonser', label: 'AI-skrivna jobbannonser' },
    { slug: 'kandidatmatchning',  suffix: 'matchning', label: 'kandidatmatchning' },
  ],
};

const BASE: BaseTool[] = [
  // ── Juridik ───────────────────────────────────────────────────
  {
    baseSlug: 'harvey-ai', yrkesroll: 'juridik', brand: 'Harvey AI', company: 'Harvey', founded: 2022, hq: 'San Francisco, USA',
    score: 9.4, fallbackUrl: 'https://www.harvey.ai',
    oneliner: 'Branschledande domänmodell för stora advokatbyråer — bäst på engelska, växande på svensk juridik.',
    features: ['Domänmodell tränad på legal text', 'Multimodal hantering av dokument', 'Säkerhet i nivå med Big Law', 'Workflows för M&A, litigation och regulatory'],
    pros: ['Skarp på komplex juridisk argumentation', 'Stark dokumentförståelse', 'Snabbväxande modeller'],
    cons: ['Designat för Big Law — dyrt för småbyråer', 'Engelska först, svenska sekundärt'],
    pricing: 'Enterprise-prissättning, typiskt sex- till sjusiffrigt per byrå och år.',
    bestFor: 'Stora advokatbyråer och inhouse-team på börsbolag',
    offer: { title: 'Demo via Harveys sales-team', price: 'Enterprise från ~$100k/år' },
    tags: ['Big Law', 'Enterprise', 'Domänmodell', 'M&A'],
    useCases: ['Avtalsgranskning', 'Due diligence', 'Regulatory research', 'Litigation-strategi', 'Drafting'],
    label: 'Redaktionens val', logo: 'bg-violet-700',
  },
  {
    baseSlug: 'lexis-ai', yrkesroll: 'juridik', brand: 'Lexis+ AI', company: 'LexisNexis', founded: 1973, hq: 'New York, USA',
    score: 9.0, fallbackUrl: 'https://www.lexisnexis.com/lexis-plus-ai',
    oneliner: 'LexisNexis AI-lager ovanpå världens största juridiska databas — bäst för citerbar research.',
    features: ['Direktåtkomst till Lexis full-text-databas', 'Hallucination-skydd via citation grounding', 'Drafting och summering', 'Cross-jurisdictional research'],
    pros: ['Auktoritativ källtäckning', 'Inbyggd citation-validering', 'Stark juristworkflow'],
    cons: ['Lexis-licens krävs', 'Bäst för anglo-rätt; svensk täckning tunnare'],
    pricing: 'Pris ovanpå Lexis-prenumeration — typiskt $200-500/användare/månad utöver baspaketet.',
    bestFor: 'Advokater som redan jobbar i Lexis',
    offer: { title: 'Demo via Lexis-säljare', price: 'Tillägg från ~$200/anv/mån' },
    tags: ['Big Database', 'Citerbar', 'Research', 'Lexis'],
    useCases: ['Rättsutredningar', 'Citation-validering', 'Cross-jurisdictional', 'Brief-drafting', 'Compliance-research'],
    label: 'Bäst för research', logo: 'bg-red-700',
  },
  {
    baseSlug: 'casetext', yrkesroll: 'juridik', brand: 'Casetext', company: 'Thomson Reuters (Casetext)', founded: 2013, hq: 'San Francisco, USA',
    score: 8.8, fallbackUrl: 'https://casetext.com',
    oneliner: 'CoCounsel-assistenten från Casetext — köptes upp av Thomson Reuters och integreras nu med Westlaw.',
    features: ['CoCounsel: AI-assistent för juristworkflow', 'Document review och drafting', 'Westlaw-integration på väg', 'Stark på US-federal case law'],
    pros: ['Beprövad GPT-4-baserad workflow', 'Tight integration med Westlaw', 'Stor user base'],
    cons: ['Fokus på US-rätt', 'Svensk täckning saknas i praktiken'],
    pricing: 'Enterprise-prissättning från $250/användare/månad. Volume-rabatter via Thomson Reuters.',
    bestFor: 'US-byråer och inhouse på multinationella bolag',
    offer: { title: '14 dagar trial', price: 'Från $250/anv/mån' },
    tags: ['CoCounsel', 'Thomson Reuters', 'Westlaw', 'US case law'],
    useCases: ['Document review', 'Deposition prep', 'Memo drafting', 'Case research', 'Contract analysis'],
    label: 'Bäst för US-rätt', logo: 'bg-blue-700',
  },
  {
    baseSlug: 'spellbook', yrkesroll: 'juridik', brand: 'Spellbook', company: 'Rally Legal', founded: 2018, hq: 'St. John\'s, Kanada',
    score: 8.7, fallbackUrl: 'https://www.spellbook.legal',
    oneliner: 'Word-tilläggssprängd AI för transactional lawyers — drafting och review direkt i dokumentet.',
    features: ['Microsoft Word add-in', 'Redline + draft i samma flöde', 'Stark på commercial contracts', 'Snabb adoption-kurva'],
    pros: ['Lever i juristernas faktiska verktyg (Word)', 'Inga separat-app att lära sig', 'Solid drafting'],
    cons: ['Bara Word-arbete', 'Mindre stark utanför kommersiella avtal'],
    pricing: 'Pris från $129/användare/månad, Enterprise vid förfrågan.',
    bestFor: 'Transactional lawyers och mid-size firms',
    offer: { title: 'Gratis trial', price: 'Från $129/anv/mån' },
    tags: ['Word add-in', 'Drafting', 'Transactional', 'Commercial'],
    useCases: ['Avtalsdrafting', 'Redlining', 'Clause-library', 'Negotiation-stöd', 'NDA-flöden'],
    label: 'Bäst i Word', logo: 'bg-amber-700',
  },
  {
    baseSlug: 'legalzoom-ai', yrkesroll: 'juridik', brand: 'LegalZoom AI', company: 'LegalZoom', founded: 2001, hq: 'Glendale, USA',
    score: 7.6, fallbackUrl: 'https://www.legalzoom.com',
    oneliner: 'AI-lager ovanpå LegalZooms DIY-juridiktjänst — för småföretagare som vill ta sig själv genom enkla ärenden.',
    features: ['AI-vägledd dokumentgenerering', 'Enkel registrering av bolag', 'Standardavtal med assist', 'Inbyggd jurist on demand'],
    pros: ['Tillgängligt för icke-jurister', 'Snabb start för småföretagare', 'Pris-effektivt för enkla ärenden'],
    cons: ['Ej för komplexa frågor', 'Bäst för US-jurisdiction'],
    pricing: 'Från ~$50-200 per dokument, eller månadsplan från $50/mån.',
    bestFor: 'Småföretagare och solopreneurer i USA',
    offer: { title: 'Pay-per-document eller månadsabonnemang', price: 'Från ~$50/dokument' },
    tags: ['DIY', 'Småföretag', 'US-jurisdiction', 'Pay-per-use'],
    useCases: ['Bolagsregistrering', 'NDA-mallar', 'Anställningsavtal-mallar', 'Trademark-ansökan', 'Wills'],
    label: 'Bäst för DIY', logo: 'bg-emerald-700',
  },
  {
    baseSlug: 'ironclad-ai', yrkesroll: 'juridik', brand: 'Ironclad AI', company: 'Ironclad', founded: 2014, hq: 'San Francisco, USA',
    score: 8.9, fallbackUrl: 'https://ironcladapp.com',
    oneliner: 'Contract Lifecycle Management (CLM) med AI för stora juridiska avdelningar.',
    features: ['Full CLM-plattform', 'AI-review av inkomna avtal', 'Smart Import av legacy-portfolio', 'Approval-workflows och e-signering'],
    pros: ['Bredast CLM-funktionalitet', 'Stark integration med Salesforce/Workday', 'Mogen produkt'],
    cons: ['Enterprise-pris', 'Implementation tar veckor till månader'],
    pricing: 'Custom enterprise-prissättning. Typiskt $25k-200k+/år.',
    bestFor: 'Mid-market till enterprise med högt avtalsflöde',
    offer: { title: 'Demo via sales', price: 'Custom — typiskt $25k+/år' },
    tags: ['CLM', 'Enterprise', 'Workflows', 'E-signering'],
    useCases: ['Contract lifecycle', 'Bulk-review', 'Approval-workflows', 'Legacy-import', 'Compliance-tracking'],
    label: 'Bäst CLM enterprise', logo: 'bg-indigo-700',
  },
  {
    baseSlug: 'contractpodai', yrkesroll: 'juridik', brand: 'ContractPodAi', company: 'ContractPodAi', founded: 2012, hq: 'New York / London',
    score: 8.5, fallbackUrl: 'https://contractpodai.com',
    oneliner: 'CLM-plattform med fokus på Leah AI-assistenten — populär hos UK/EU-team.',
    features: ['Leah AI assistant', 'Full CLM med MS Word-stöd', 'EU/GDPR-fokus', 'Stark i UK/EU-marknaden'],
    pros: ['EU-baserat alternativ till Ironclad', 'Bra Word-flöde', 'GDPR-fokus'],
    cons: ['Mindre brett ekosystem', 'UI-modernhet efter konkurrenter'],
    pricing: 'Enterprise-prissättning från ~$30k/år.',
    bestFor: 'EU/UK-bolag och europeiska juridik-avdelningar',
    offer: { title: 'Demo via sales', price: 'Från ~$30k/år' },
    tags: ['CLM', 'EU/UK', 'GDPR', 'Word'],
    useCases: ['Contract lifecycle', 'Approval-workflows', 'EU-compliance', 'Risk-flagging', 'Vendor-management'],
    label: 'Bäst för EU/UK', logo: 'bg-sky-700',
  },
  {
    baseSlug: 'luminance', yrkesroll: 'juridik', brand: 'Luminance', company: 'Luminance', founded: 2015, hq: 'Cambridge, UK',
    score: 8.6, fallbackUrl: 'https://www.luminance.com',
    oneliner: 'AI för granskning av avtal och due diligence — Cambridge-baserat med stark europeisk närvaro.',
    features: ['Avtalsanalys på 80+ språk', 'Anomalidetektion mot peer-grupp', 'Due diligence-pipeline', 'Privata LLM-deployment'],
    pros: ['Bästa för cross-border DD', 'Privacy-läge med on-prem möjligt', 'Bred språkstöd'],
    cons: ['Brant inlärningskurva', 'Pris kräver volym'],
    pricing: 'Enterprise-prissättning. Typiskt £30k+/år beroende på volym.',
    bestFor: 'M&A-team och multinationella inhouse-funktioner',
    offer: { title: 'Demo via sales', price: 'Från ~£30k/år' },
    tags: ['80+ språk', 'On-prem', 'M&A', 'DD'],
    useCases: ['Due diligence', 'Cross-border contract review', 'Risk-detection', 'Regulatory analysis', 'M&A-pipeline'],
    label: 'Bäst för DD cross-border', logo: 'bg-rose-700',
  },
  {
    baseSlug: 'ebrevia', yrkesroll: 'juridik', brand: 'eBrevia', company: 'Donnelley Financial (eBrevia)', founded: 2012, hq: 'Stamford, USA',
    score: 7.9, fallbackUrl: 'https://ebrevia.com',
    oneliner: 'Extraktion av nyckelvillkor från stora avtalsportföljer — populärt under DD och regulatory exercises.',
    features: ['Klausul- och datapunkts-extraktion', 'Hög volymhantering', 'Anpassningsbara extraktionsmallar', 'Donnelley-integration för finans'],
    pros: ['Beprövad i finans-due diligence', 'Snabb pipeline', 'God audit-trail'],
    cons: ['Mindre AI-modernt än Luminance', 'Bäst i finans/M&A-context'],
    pricing: 'Enterprise-prissättning. Custom quote.',
    bestFor: 'Finansiella DD-team och Big4 advisory',
    offer: { title: 'Demo via sales', price: 'Custom enterprise' },
    tags: ['Extraktion', 'Finans-DD', 'Donnelley', 'Audit'],
    useCases: ['DD-extraktion', 'Lease-review', 'Regulatory exercises', 'Contract abstraction', 'M&A pipeline'],
    label: 'Bäst för finans-DD', logo: 'bg-zinc-700',
  },
  {
    baseSlug: 'kira-systems', yrkesroll: 'juridik', brand: 'Kira Systems', company: 'Litera (Kira)', founded: 2011, hq: 'Toronto, Kanada',
    score: 8.4, fallbackUrl: 'https://kirasystems.com',
    oneliner: 'AI för avtalsanalys, akviresad av Litera och nu integrerad i deras juristsvit.',
    features: ['1000+ förtränade smart fields', 'Litera Suite-integration', 'Stark i M&A och fastighet', 'Enterprise-säkerhet'],
    pros: ['Stort bibliotek av extraktionsmodeller', 'Mogen produkt', 'God Litera-integration'],
    cons: ['Enterprise-onboarding', 'UI på äldre sidan'],
    pricing: 'Enterprise. Custom quote — typiskt $50k+/år.',
    bestFor: 'M&A-team som redan kör Litera-svit',
    offer: { title: 'Demo via Litera-sales', price: 'Från ~$50k/år' },
    tags: ['Litera', 'Smart fields', 'M&A', 'Real estate'],
    useCases: ['DD-extraktion', 'Lease-abstraction', 'Contract review', 'Compliance audits', 'M&A pipeline'],
    label: 'Bäst för Litera-stack', logo: 'bg-fuchsia-700',
  },

  // ── Kundservice ──────────────────────────────────────────────
  {
    baseSlug: 'intercom-ai', yrkesroll: 'kundservice', brand: 'Intercom AI', company: 'Intercom', founded: 2011, hq: 'San Francisco / Dublin',
    score: 9.3, fallbackUrl: 'https://www.intercom.com',
    oneliner: 'Fin AI Agent löser ärenden helt automatiskt — branschledande på faktisk ärendelösning.',
    features: ['Fin AI Agent — autonom ärendelösning', 'Inbox + Help Center i ett', 'Outbound messaging', 'Stark proaktiv UX'],
    pros: ['Marknadsledande på autonom resolution', 'Modern produkt', 'Stark messaging-DNA'],
    cons: ['Pris hoppar snabbt vid skala', 'AI-tier separat från base'],
    pricing: 'Essential från $39/seat. Fin AI: $0.99 per resolution. Enterprise custom.',
    bestFor: 'SaaS-bolag och scale-ups med modernt support-tänk',
    offer: { title: '14 dagar trial', price: 'Från $39/seat + Fin $0.99/resolution' },
    tags: ['Fin AI', 'Resolution-based', 'Messaging', 'Modern'],
    useCases: ['Autonom ärendelösning', 'Tier-1 support', 'Outbound retention', 'Onboarding-flöden', 'Proaktiv hjälp'],
    label: 'Redaktionens val', logo: 'bg-indigo-700',
  },
  {
    baseSlug: 'zendesk-ai', yrkesroll: 'kundservice', brand: 'Zendesk AI', company: 'Zendesk', founded: 2007, hq: 'San Francisco, USA',
    score: 9.0, fallbackUrl: 'https://www.zendesk.com',
    oneliner: 'AI-funktioner inbyggda i ärendehanteringen som driver hälften av världens helpdesks.',
    features: ['Advanced AI add-on', 'Autoresponder + suggested replies', 'Intent detection och routing', 'Omnichannel (chat, mejl, telefon)'],
    pros: ['Branschstandard helpdesk', 'Bred integrationsmarknad', 'Mogen AI på toppen av befintliga flöden'],
    cons: ['AI är tilläggsmodul, inte inbyggt', 'Stora team får snabbt premium-prislapp'],
    pricing: 'Suite Team $55/agent. AI add-on $50/agent extra. Enterprise från $115+.',
    bestFor: 'Etablerade kundservice-team med Zendesk redan',
    offer: { title: '14 dagar trial', price: 'Suite Team $55 + AI $50/agent/mån' },
    tags: ['Omnichannel', 'Helpdesk', 'Branschstandard', 'Add-on AI'],
    useCases: ['Ärendehantering', 'Routing', 'Autoresponder', 'Omnichannel-support', 'Knowledge-base assist'],
    label: 'Branschstandard', logo: 'bg-emerald-700',
  },
  {
    baseSlug: 'freshdesk-ai', yrkesroll: 'kundservice', brand: 'Freshdesk AI', company: 'Freshworks', founded: 2010, hq: 'San Mateo / Chennai',
    score: 8.6, fallbackUrl: 'https://www.freshworks.com/freshdesk',
    oneliner: 'Freshworks helpdesk med Freddy AI — bra prisvärde mot Zendesk på mid-market.',
    features: ['Freddy AI Copilot för agenter', 'Bot-flow builder', 'Omnichannel-support', 'God Slack/Teams-integration'],
    pros: ['Konkurrenskraftigt pris', 'Snabb implementation', 'Snyggt UI'],
    cons: ['Mindre community än Zendesk', 'Avancerad routing kräver Enterprise'],
    pricing: 'Growth $15/agent, Pro $49, Enterprise $79. Freddy AI ingår i högre tiers.',
    bestFor: 'Mid-market som vill ha Zendesk-funktionalitet billigare',
    offer: { title: '21 dagar trial', price: 'Growth $15/agent/mån' },
    tags: ['Freddy AI', 'Mid-market', 'Affordable', 'Omnichannel'],
    useCases: ['Ärendehantering', 'Agent-copilot', 'Chatbot-flöden', 'Knowledge-base', 'Field service'],
    label: 'Bästa pris-prestanda', logo: 'bg-amber-600',
  },
  {
    baseSlug: 'tidio', yrkesroll: 'kundservice', brand: 'Tidio', company: 'Tidio', founded: 2013, hq: 'San Francisco / Szczecin',
    score: 8.2, fallbackUrl: 'https://www.tidio.com',
    oneliner: 'Lyro AI och chatbot-builder för småföretag — bäst för Shopify och e-handel.',
    features: ['Lyro AI conversation engine', 'Shopify-integration', 'Live chat + bot i ett', 'Visual flow-builder'],
    pros: ['Bäst för småhandlare', 'Snabb start', 'Generös gratisversion'],
    cons: ['Smalt för enterprise-volym', 'Färre integrationer än Zendesk'],
    pricing: 'Free-plan finns. Starter $29, Growth $59, Plus $749/mån för Lyro AI i skala.',
    bestFor: 'E-handlare på Shopify/WooCommerce',
    offer: { title: '7 dagar premium-trial + free-tier', price: 'Free / Starter $29/mån' },
    tags: ['Lyro AI', 'Shopify', 'SMB', 'E-handel'],
    useCases: ['Chatbot e-handel', 'Live chat', 'Cart-recovery', 'FAQ-automation', 'Shopify-stöd'],
    label: 'Bäst för småhandel', logo: 'bg-sky-600',
  },
  {
    baseSlug: 'drift', yrkesroll: 'kundservice', brand: 'Drift', company: 'Salesloft (Drift)', founded: 2015, hq: 'Boston, USA',
    score: 8.0, fallbackUrl: 'https://www.drift.com',
    oneliner: 'Conversational marketing-bot köpt av Salesloft — fokus är på leads, inte renodlad support.',
    features: ['Conversational bots för leadgen', 'Account-based routing', 'Drift Engage för on-site engagement', 'Salesloft-integration'],
    pros: ['Bäst för B2B-leadgen via chat', 'God account-routing', 'Conversational marketing-pionjär'],
    cons: ['Inte renodlad support', 'Funkar bäst i sälj-tunga flöden'],
    pricing: 'Premium $2500/mån, Advanced $5000, Enterprise custom. Inkluderar inte Salesloft-licens.',
    bestFor: 'B2B-säljteam med inbound-fokus',
    offer: { title: 'Demo via sales', price: 'Från ~$2500/mån' },
    tags: ['Conversational marketing', 'B2B', 'Leadgen', 'Salesloft'],
    useCases: ['Inbound leadgen', 'Account-based marketing', 'Sales-chat', 'Outbound nurture', 'Engagement-routing'],
    label: 'Bäst för B2B-leadgen', logo: 'bg-violet-600',
  },
  {
    baseSlug: 'chatbot-com', yrkesroll: 'kundservice', brand: 'ChatBot.com', company: 'LiveChat Inc.', founded: 2002, hq: 'Wrocław, Polen',
    score: 7.8, fallbackUrl: 'https://www.chatbot.com',
    oneliner: 'No-code chatbot builder från LiveChat-koncernen — bygg flöden visuellt utan att skriva kod.',
    features: ['Visuell flow-builder', 'Inbyggd LiveChat-integration', 'Templates för vanliga branscher', 'GPT-4o-stöd i Bot 2.0'],
    pros: ['Inga utvecklare behövs', 'Bra mall-bibliotek', 'Snabb implementation'],
    cons: ['Mindre AI-driven än Tidio Lyro', 'Behöver LiveChat för full kraft'],
    pricing: 'Starter $52/mån (1000 chats), Team $142/mån, Business $424, Enterprise custom.',
    bestFor: 'SMB som vill ha visuell flow-builder',
    offer: { title: '14 dagar trial', price: 'Starter $52/mån' },
    tags: ['No-code', 'Flow builder', 'LiveChat', 'Templates'],
    useCases: ['FAQ-automation', 'Lead-qualification', 'Booking-flöden', 'Survey-bot', 'E-handel-FAQ'],
    label: 'Bäst no-code', logo: 'bg-teal-700',
  },
  {
    baseSlug: 'forethought', yrkesroll: 'kundservice', brand: 'Forethought', company: 'Forethought', founded: 2017, hq: 'San Francisco, USA',
    score: 8.4, fallbackUrl: 'https://forethought.ai',
    oneliner: 'AI-first kundservice-plattform — fokus på autonom resolution och ärendeprediktion.',
    features: ['SupportGPT-modell', 'Autoflows för svåra ärenden', 'Sentiment- och prediktionsmotor', 'Solid Zendesk/Salesforce-integration'],
    pros: ['Stark autonom resolution', 'Smart prediktion', 'Bra Zendesk-tillägg'],
    cons: ['Smalt mid-market segment', 'Mindre känt utanför Bay Area'],
    pricing: 'Custom enterprise-pricing. Typiskt från ~$30k/år.',
    bestFor: 'Modernt mid-market support-team som vill toppa Zendesk med AI',
    offer: { title: 'Demo via sales', price: 'Från ~$30k/år' },
    tags: ['SupportGPT', 'Autonom', 'Zendesk-tillägg', 'Prediktion'],
    useCases: ['Autonom resolution', 'Sentiment-detection', 'Ärendeprediktion', 'Smart routing', 'Knowledge-bridging'],
    label: 'Bäst Zendesk-toppning', logo: 'bg-rose-600',
  },
  {
    baseSlug: 'aisera', yrkesroll: 'kundservice', brand: 'Aisera', company: 'Aisera', founded: 2017, hq: 'Palo Alto, USA',
    score: 8.5, fallbackUrl: 'https://aisera.com',
    oneliner: 'AI-service desk för IT- och HR-support i stora företag — fokus på autonom internsupport.',
    features: ['Conversational AI för IT/HR/finans', 'AIOps-integration', 'ServiceNow-djupintegration', 'Branchen-specifika modeller'],
    pros: ['Stark inom intern service desk', 'God ServiceNow-integration', 'Enterprise-säkerhet'],
    cons: ['Premium-prislapp', 'Bäst för stora företag'],
    pricing: 'Enterprise-prissättning, custom quote. Typiskt $50k-200k+/år.',
    bestFor: 'Stora företag med IT/HR helpdesk-behov',
    offer: { title: 'Demo via sales', price: 'Custom enterprise' },
    tags: ['Internsupport', 'ServiceNow', 'IT/HR', 'Enterprise'],
    useCases: ['IT helpdesk', 'HR-support', 'Finance-support', 'Self-service-portaler', 'AIOps-integration'],
    label: 'Bäst intern service desk', logo: 'bg-fuchsia-600',
  },
  {
    baseSlug: 'salesforce-einstein', yrkesroll: 'kundservice', brand: 'Salesforce Einstein', company: 'Salesforce', founded: 1999, hq: 'San Francisco, USA',
    score: 8.7, fallbackUrl: 'https://www.salesforce.com/products/einstein-ai-solutions',
    oneliner: 'Salesforce Einstein och Agentforce — AI-lagret över världens största CRM, nu med autonoma agenter.',
    features: ['Einstein Copilot för agenter', 'Agentforce autonoma agenter', 'Trust Layer för data-säkerhet', 'Full Salesforce-integration'],
    pros: ['Djup Salesforce-integration', 'Stark säkerhet (Trust Layer)', 'Autonoma agenter på väg'],
    cons: ['Kräver Salesforce-licens', 'Komplext om man inte redan kör Salesforce'],
    pricing: 'Einstein 1 Service Edition från $500/användare/mån. Agentforce från $2/conversation.',
    bestFor: 'Salesforce-kunder med Service Cloud',
    offer: { title: 'Inkluderad i högre Service Cloud-tiers', price: 'Från $500/anv/mån (Service)' },
    tags: ['Einstein', 'Agentforce', 'Salesforce', 'Trust Layer'],
    useCases: ['Service Cloud-AI', 'Autonoma agenter', 'Case-routing', 'Knowledge-management', 'Sales-service-koppling'],
    label: 'Bäst för Salesforce-stack', logo: 'bg-blue-600',
  },
  {
    baseSlug: 'hubspot-ai', yrkesroll: 'kundservice', brand: 'HubSpot AI', company: 'HubSpot', founded: 2006, hq: 'Cambridge, USA',
    score: 8.5, fallbackUrl: 'https://www.hubspot.com',
    oneliner: 'Breeze AI över HubSpots Service Hub — bäst för SMB som redan kör HubSpot CRM.',
    features: ['Breeze Copilot för agenter', 'Service Hub med chatbot', 'Knowledge-base assistant', 'Customer Portal med AI'],
    pros: ['Bra för SMB som redan kör HubSpot', 'AI ingår i högre tiers', 'Smidigt över sälj/marknad/service'],
    cons: ['Bäst när du redan kör HubSpot', 'Avancerad routing saknas mot Zendesk'],
    pricing: 'Service Hub Starter $20, Pro $100/seat, Enterprise $150+. Breeze AI ingår.',
    bestFor: 'SMB med HubSpot-stack',
    offer: { title: '14 dagar trial', price: 'Service Hub Starter $20/mån' },
    tags: ['Breeze', 'Service Hub', 'SMB', 'CRM-integration'],
    useCases: ['Service Hub-AI', 'Customer Portal', 'KB-assistant', 'Chatbot-flöden', 'Tightning sälj/service'],
    label: 'Bäst för HubSpot-stack', logo: 'bg-orange-700',
  },

  // ── Rekrytering ──────────────────────────────────────────────
  {
    baseSlug: 'workday-ai', yrkesroll: 'rekrytering', brand: 'Workday AI', company: 'Workday', founded: 2005, hq: 'Pleasanton, USA',
    score: 9.0, fallbackUrl: 'https://www.workday.com',
    oneliner: 'Workdays HCM-plattform med inbyggd AI-rekrytering — branschstandard för stora företag.',
    features: ['AI-driven candidate-discovery', 'Recruiting Agent autonom screening', 'Skills Cloud + matching', 'End-to-end HCM'],
    pros: ['Branschstandard för stora företag', 'AI fully integrated', 'Stark compliance'],
    cons: ['Lågfart för ändringar', 'Enterprise-pris'],
    pricing: 'Custom enterprise — typiskt $30-100+ per anställd och år.',
    bestFor: 'Företag med 1000+ anställda som redan kör Workday',
    offer: { title: 'Demo via Workday-sales', price: 'Från ~$30/anställd/år' },
    tags: ['Enterprise', 'HCM', 'Skills Cloud', 'Recruiting Agent'],
    useCases: ['End-to-end rekrytering', 'Talent management', 'Skills-mapping', 'Internal mobility', 'Compliance-rapportering'],
    label: 'Branschstandard enterprise', logo: 'bg-orange-700',
  },
  {
    baseSlug: 'hirevue', yrkesroll: 'rekrytering', brand: 'HireVue', company: 'HireVue', founded: 2004, hq: 'South Jordan, USA',
    score: 8.5, fallbackUrl: 'https://www.hirevue.com',
    oneliner: 'AI-driven video-intervju och assessment — pionjär inom on-demand-interviews.',
    features: ['Asynkron videointervju', 'Game-based assessments', 'Coding-tests', 'Strukturerad AI-analys'],
    pros: ['Skalbar screening', 'Bra för volym-rekrytering', 'Mogen produkt'],
    cons: ['Etikdebatten kring AI-analys', 'Mindre relevant för senior-roller'],
    pricing: 'Custom enterprise. Typiskt från ~$25k/år.',
    bestFor: 'Volym-rekrytering (consulting, banker, retail-management)',
    offer: { title: 'Demo via sales', price: 'Från ~$25k/år' },
    tags: ['Videointervju', 'Volym', 'Assessment', 'On-demand'],
    useCases: ['On-demand-intervjuer', 'Game-based assessments', 'Coding-screening', 'Campus-rekrytering', 'Diversity-screening'],
    label: 'Bäst videointervju', logo: 'bg-emerald-600',
  },
  {
    baseSlug: 'pymetrics', yrkesroll: 'rekrytering', brand: 'Pymetrics', company: 'Harver (Pymetrics)', founded: 2013, hq: 'New York, USA',
    score: 8.0, fallbackUrl: 'https://www.harver.com',
    oneliner: 'Neurovetenskapsbaserade game-assessments för bias-reducerad screening — nu del av Harver.',
    features: ['12 neurovetenskaps-baserade spel', 'Audit-trail för bias', 'Fairness-modell över etnicitet/kön', 'Personalitets- och kognitiv profil'],
    pros: ['Vetenskapligt förankrad', 'Stark bias-reduktion', 'Bra för att hitta otraditionella kandidater'],
    cons: ['Smalt fokus (assessment, ej ATS)', 'Kräver volym för att löna sig'],
    pricing: 'Custom enterprise. Från ~$15k/år.',
    bestFor: 'Stora rekryteringsbolag med diversitetsmål',
    offer: { title: 'Demo via Harver-sales', price: 'Från ~$15k/år' },
    tags: ['Neuroscience', 'Bias-reduktion', 'Fairness', 'Game-based'],
    useCases: ['Bias-reducerad screening', 'Diversitetsmål', 'Campus-volym', 'Personality-assessment', 'Talent-pool-utvärdering'],
    label: 'Bäst för bias-reduktion', logo: 'bg-fuchsia-600',
  },
  {
    baseSlug: 'greenhouse-ai', yrkesroll: 'rekrytering', brand: 'Greenhouse AI', company: 'Greenhouse', founded: 2012, hq: 'New York, USA',
    score: 8.9, fallbackUrl: 'https://www.greenhouse.com',
    oneliner: 'Greenhouse ATS med AI-lager — favorit hos tech-bolag och scale-ups.',
    features: ['Greenhouse Recruiting AI', 'Strukturerade intervjuer', 'CRM för talent pool', 'Solid integration-marketplace'],
    pros: ['Branschledande ATS', 'Bra strukturerad rekryteringsprocess', 'Modern UX'],
    cons: ['AI är yngre än ATS-stommen', 'Enterprise-pris'],
    pricing: 'Custom enterprise — typiskt $5-10k/månad för 100-anställdsbolag.',
    bestFor: 'Tech-scale-ups och moderna HR-team',
    offer: { title: 'Demo via Greenhouse-sales', price: 'Från ~$5k/mån' },
    tags: ['ATS', 'Tech-scale-ups', 'Strukturerat', 'Modern UX'],
    useCases: ['ATS-flöden', 'Strukturerade intervjuer', 'Talent CRM', 'Diversity-tracking', 'Skills-bedömning'],
    label: 'Bäst ATS för tech', logo: 'bg-green-700',
  },
  {
    baseSlug: 'lever-ai', yrkesroll: 'rekrytering', brand: 'Lever AI', company: 'Employ Inc. (Lever)', founded: 2012, hq: 'San Francisco, USA',
    score: 8.4, fallbackUrl: 'https://www.lever.co',
    oneliner: 'Lever ATS + CRM med AI-funktioner — fokus på outbound-sourcing och nurture.',
    features: ['Lever Talent Intelligence', 'CRM med nurture-flöden', 'Sourcing automation', 'EEO/OFCCP-reporting'],
    pros: ['Stark sourcing-funktionalitet', 'Bra för outbound-tunga team', 'Solid talent CRM'],
    cons: ['Mindre community än Greenhouse', 'AI-features yngre'],
    pricing: 'Custom — typiskt $4-8k/mån för 100-anställdsbolag.',
    bestFor: 'Bolag med stora outbound-sourcing-pipelines',
    offer: { title: 'Demo via sales', price: 'Från ~$4k/mån' },
    tags: ['ATS+CRM', 'Sourcing', 'Outbound', 'Nurture'],
    useCases: ['Outbound-sourcing', 'Talent CRM', 'Pipeline-management', 'Compliance-reporting', 'Nurture-flöden'],
    label: 'Bäst för sourcing', logo: 'bg-amber-700',
  },
  {
    baseSlug: 'beamery', yrkesroll: 'rekrytering', brand: 'Beamery', company: 'Beamery', founded: 2014, hq: 'London, UK',
    score: 8.6, fallbackUrl: 'https://www.beamery.com',
    oneliner: 'Talent Lifecycle Management-plattform med skills-AI — populärast hos stora multinationella företag.',
    features: ['Talent Cloud (skills + people)', 'Skills-based-matching-modell', 'CRM + nurture över hela livscykeln', 'Stark i Europa/UK'],
    pros: ['Bred talent lifecycle-täckning', 'Skills-baserad approach', 'EU-fokus'],
    cons: ['Enterprise-pris', 'Implementation kräver konsult'],
    pricing: 'Custom enterprise — typiskt $50-200k+/år.',
    bestFor: 'Multinationella företag med stor talent pool',
    offer: { title: 'Demo via sales', price: 'Från ~$50k/år' },
    tags: ['Talent Cloud', 'Skills', 'Europe', 'Multinationals'],
    useCases: ['Talent lifecycle', 'Skills-mapping', 'Internal mobility', 'Diversity-pipelines', 'EU-rekrytering'],
    label: 'Bäst multinationellt', logo: 'bg-violet-700',
  },
  {
    baseSlug: 'fetcher', yrkesroll: 'rekrytering', brand: 'Fetcher', company: 'Fetcher', founded: 2014, hq: 'New York, USA',
    score: 8.0, fallbackUrl: 'https://fetcher.ai',
    oneliner: 'Outbound-sourcing-AI som hittar och engagerar passiva kandidater åt dig automatiskt.',
    features: ['Outbound-sourcing på autopilot', 'Email-sequencer för passiva kandidater', 'Diversity-options inbyggt', 'ATS-integration'],
    pros: ['Snabbar upp passiv sourcing', 'Bra för småteam', 'Tydlig diversity-funktion'],
    cons: ['Bara outbound-sourcing (ej ATS)', 'Inte för executive-rekrytering'],
    pricing: 'Pro $549/mån, Amplify $1099/mån. Custom enterprise.',
    bestFor: 'Småteam som behöver volym på passiv kandidat-outreach',
    offer: { title: 'Demo via sales', price: 'Pro $549/mån' },
    tags: ['Outbound', 'Sourcing', 'Passive candidates', 'Diversity'],
    useCases: ['Passiv kandidat-sourcing', 'Email-nurture', 'Diversity-pipelines', 'Småteam-rekrytering', 'Pipeline-volume'],
    label: 'Bäst passiv sourcing', logo: 'bg-cyan-700',
  },
  {
    baseSlug: 'paradox', yrkesroll: 'rekrytering', brand: 'Paradox', company: 'Paradox', founded: 2016, hq: 'Scottsdale, USA',
    score: 8.7, fallbackUrl: 'https://www.paradox.ai',
    oneliner: 'Olivia-conversationsbot för volym-rekrytering — McDonalds och stora retail-team litar på den.',
    features: ['Olivia conversational AI', 'SMS + chat-orchestrering', 'Scheduling automation', 'Tex-/röst-screening'],
    pros: ['Bäst för retail/QSR-volym', 'Stark scheduling-automation', 'Mobil-first'],
    cons: ['Mindre relevant för senior/profession-roller', 'Specialiserat på volym'],
    pricing: 'Custom enterprise — typiskt $5-50k/mån beroende på volym.',
    bestFor: 'Retail, QSR, manufacturing och annan volym-rekrytering',
    offer: { title: 'Demo via sales', price: 'Custom från ~$5k/mån' },
    tags: ['Olivia', 'SMS', 'QSR', 'Retail'],
    useCases: ['Volym-rekrytering', 'SMS-screening', 'Scheduling', 'Retail-rekrytering', 'On-demand-intervjuer'],
    label: 'Bäst för volym', logo: 'bg-pink-700',
  },
  {
    baseSlug: 'eightfold-ai', yrkesroll: 'rekrytering', brand: 'Eightfold AI', company: 'Eightfold AI', founded: 2016, hq: 'Santa Clara, USA',
    score: 9.0, fallbackUrl: 'https://eightfold.ai',
    oneliner: 'Talent Intelligence Platform med djup AI — bäst-i-klassen på skills-matching och intern rörlighet.',
    features: ['Talent Intelligence Platform', 'Deep learning över 1 miljard kandidater', 'Internal mobility-modul', 'Skills-modeller per bransch'],
    pros: ['Marknadens djupaste AI-modell', 'Stark internal mobility', 'Branschspecifika modeller'],
    cons: ['Enterprise-pris', 'Implementation kräver konsult'],
    pricing: 'Custom enterprise — typiskt $100-500k+/år.',
    bestFor: 'Stora företag med komplexa skills-pipelines',
    offer: { title: 'Demo via sales', price: 'Custom enterprise' },
    tags: ['Talent Intelligence', 'Deep learning', 'Internal mobility', 'Skills'],
    useCases: ['Skills-matching', 'Internal mobility', 'Diversity-pipelines', 'Talent-prediktion', 'M&A-talent-integration'],
    label: 'Djupast AI', logo: 'bg-indigo-700',
  },
  {
    baseSlug: 'seekout', yrkesroll: 'rekrytering', brand: 'SeekOut', company: 'SeekOut', founded: 2017, hq: 'Bellevue, USA',
    score: 8.5, fallbackUrl: 'https://seekout.com',
    oneliner: 'Talent search-motor med AI för att hitta nålar i höstacken — bäst för teknik- och sjukvårdsrekrytering.',
    features: ['600M+ kandidatprofiler', 'GenAI-powered search', 'Diversity-filter', 'Healthcare och tech-specialiserad'],
    pros: ['Bästa kandidat-databasen', 'Skarp på tech/sjukvård', 'Diversity-funktioner inbyggt'],
    cons: ['Search-only (ej ATS)', 'Premium-pris'],
    pricing: 'Custom enterprise — typiskt $1-5k/seat/månad.',
    bestFor: 'Tech- och sjukvårds-rekryterare med svår-att-hitta roller',
    offer: { title: 'Demo via sales', price: 'Från ~$1k/seat/mån' },
    tags: ['Talent search', 'Tech', 'Healthcare', 'Diversity'],
    useCases: ['Svår-att-hitta tech-talanger', 'Sjukvårdsrekrytering', 'Diversitets-sourcing', 'Niche-roller', 'Boolean-search-automation'],
    label: 'Bäst tech/sjukvård search', logo: 'bg-rose-700',
  },
];

/** Expand each base tool into one YrkeTool per subcategory of its yrkesroll. */
export const EXTENDED_TOOLS: YrkeTool[] = BASE.flatMap((t) =>
  SUBCATS_BY_ROLE[t.yrkesroll].map((sub) => {
    const { baseSlug, yrkesroll: _y, ...common } = t;
    void _y;
    return {
      ...common,
      slug: `${baseSlug}-${sub.suffix}`,
      parent: sub.slug,
      title: `${t.brand} för ${sub.label} — Recension ${new Date().getFullYear()}`,
    };
  })
);
