-- aimagasinet.se — cache for Haiku-generated AI-tool comparison copy
-- Apply via: Supabase Dashboard → SQL Editor (paste & run)
-- or via Supabase CLI: `supabase db push`
--
-- One row per /ai-verktyg/jamfor/[a]-eller-[b] page. `content` holds a JSON
-- string { intro, verdict, faqs[] } generated by scripts/generate-comparisons.ts.

create table if not exists comparisons (
  slug       text primary key,
  verktyg_a  text not null,
  verktyg_b  text not null,
  content    text,
  created_at timestamptz not null default now()
);

-- RLS: anon may read (the public RSC client fetches cached copy at build /
-- ISR time); only the service-role writes (bypasses RLS).
alter table comparisons enable row level security;

drop policy if exists "comparisons anon read" on comparisons;
create policy "comparisons anon read" on comparisons
  for select using (true);
